/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.cids.custom.nas;

import javax.swing.JFrame;

/**
 * DOCUMENT ME!
 *
 * @author   daniel
 * @version  $Revision$, $Date$
 */
public class NasFeePreviewPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private boolean isPointType;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnzahlTitle;
    private javax.swing.JLabel lblFlurstuecke;
    private javax.swing.JLabel lblFlurstueckeAnzahl;
    private javax.swing.JLabel lblFlurstueckeGesamt;
    private javax.swing.JLabel lblGebaeude;
    private javax.swing.JLabel lblGebaeudeAnzahl;
    private javax.swing.JLabel lblGebeaudeGesamt;
    private javax.swing.JLabel lblGesamt;
    private javax.swing.JLabel lblGesamtTitle;
    private javax.swing.JLabel lblGesamtValue;
    private javax.swing.JLabel lblPunkte;
    private javax.swing.JLabel lblPunkteAnzahl;
    private javax.swing.JLabel lblPunkteGesamt;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new NasFeePreviewPanel object.
     */
    public NasFeePreviewPanel() {
        this(false);
    }

    /**
     * Creates new form NasFeePreviewPanel.
     *
     * @param  isPointType  DOCUMENT ME!
     */
    public NasFeePreviewPanel(final boolean isPointType) {
        this.isPointType = isPointType;
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @param  amount  DOCUMENT ME!
     * @param  value   DOCUMENT ME!
     */
    public void setFlurstueckLabels(final String amount, final String value) {
        lblFlurstueckeAnzahl.setText(amount);
        lblFlurstueckeGesamt.setText(value);
    }

    /**
     * DOCUMENT ME!
     *
     * @param  amount  DOCUMENT ME!
     * @param  value   DOCUMENT ME!
     */
    public void setPointLabels(final String amount, final String value) {
        lblPunkteAnzahl.setText(amount);
        lblPunkteGesamt.setText(value);
    }

    /**
     * DOCUMENT ME!
     *
     * @param  amount  DOCUMENT ME!
     * @param  value   DOCUMENT ME!
     */
    public void setGebaeudeLabels(final String amount, final String value) {
        lblGebaeudeAnzahl.setText(amount);
        lblGebeaudeGesamt.setText(value);
    }
    /**
     * DOCUMENT ME!
     *
     * @param  value  DOCUMENT ME!
     */
    public void setTotalLabel(final String value) {
        lblGesamtValue.setText(value);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        lblAnzahlTitle = new javax.swing.JLabel();
        lblGesamtTitle = new javax.swing.JLabel();
        if (!isPointType) {
            lblFlurstuecke = new javax.swing.JLabel();
        }
        if (!isPointType) {
            lblGebaeude = new javax.swing.JLabel();
        }
        if (isPointType) {
            lblPunkte = new javax.swing.JLabel();
        }
        if (!isPointType) {
            lblFlurstueckeAnzahl = new javax.swing.JLabel();
        }
        if (!isPointType) {
            lblFlurstueckeGesamt = new javax.swing.JLabel();
        }
        if (!isPointType) {
            lblGebaeudeAnzahl = new javax.swing.JLabel();
        }
        if (!isPointType) {
            lblGebeaudeGesamt = new javax.swing.JLabel();
        }
        if (isPointType) {
            lblPunkteAnzahl = new javax.swing.JLabel();
        }
        if (isPointType) {
            lblPunkteGesamt = new javax.swing.JLabel();
        }
        jPanel1 = new javax.swing.JPanel();
        lblGesamtValue = new javax.swing.JLabel();
        lblGesamt = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(new java.awt.Font("DejaVu Sans", 1, 14));                                               // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            lblTitle,
            org.openide.util.NbBundle.getMessage(NasFeePreviewPanel.class, "NasFeePreviewPanel.lblTitle.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(lblTitle, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            lblAnzahlTitle,
            org.openide.util.NbBundle.getMessage(NasFeePreviewPanel.class, "NasFeePreviewPanel.lblAnzahlTitle.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(lblAnzahlTitle, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            lblGesamtTitle,
            org.openide.util.NbBundle.getMessage(NasFeePreviewPanel.class, "NasFeePreviewPanel.lblGesamtTitle.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(lblGesamtTitle, gridBagConstraints);

        if (!isPointType) {
            org.openide.awt.Mnemonics.setLocalizedText(
                lblFlurstuecke,
                org.openide.util.NbBundle.getMessage(
                    NasFeePreviewPanel.class,
                    "NasFeePreviewPanel.lblFlurstuecke.text")); // NOI18N
        }
        if (!isPointType) {
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 2;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
            gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
            add(lblFlurstuecke, gridBagConstraints);
        }

        if (!isPointType) {
            org.openide.awt.Mnemonics.setLocalizedText(
                lblGebaeude,
                org.openide.util.NbBundle.getMessage(NasFeePreviewPanel.class, "NasFeePreviewPanel.lblGebaeude.text")); // NOI18N
        }
        if (!isPointType) {
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 3;
            gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
            add(lblGebaeude, gridBagConstraints);
        }

        if (isPointType) {
            org.openide.awt.Mnemonics.setLocalizedText(
                lblPunkte,
                org.openide.util.NbBundle.getMessage(NasFeePreviewPanel.class, "NasFeePreviewPanel.lblPunkte.text")); // NOI18N
        }
        if (isPointType) {
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 4;
            gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
            add(lblPunkte, gridBagConstraints);
        }

        if (!isPointType) {
            org.openide.awt.Mnemonics.setLocalizedText(
                lblFlurstueckeAnzahl,
                org.openide.util.NbBundle.getMessage(
                    NasFeePreviewPanel.class,
                    "NasFeePreviewPanel.lblFlurstueckeAnzahl.text")); // NOI18N
        }
        if (!isPointType) {
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 2;
            gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
            add(lblFlurstueckeAnzahl, gridBagConstraints);
        }

        if (!isPointType) {
            org.openide.awt.Mnemonics.setLocalizedText(
                lblFlurstueckeGesamt,
                org.openide.util.NbBundle.getMessage(
                    NasFeePreviewPanel.class,
                    "NasFeePreviewPanel.lblFlurstueckeGesamt.text")); // NOI18N
        }
        if (!isPointType) {
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = 2;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
            gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
            add(lblFlurstueckeGesamt, gridBagConstraints);
        }

        if (!isPointType) {
            org.openide.awt.Mnemonics.setLocalizedText(
                lblGebaeudeAnzahl,
                org.openide.util.NbBundle.getMessage(
                    NasFeePreviewPanel.class,
                    "NasFeePreviewPanel.lblGebaeudeAnzahl.text")); // NOI18N
        }
        if (!isPointType) {
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 3;
            gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
            add(lblGebaeudeAnzahl, gridBagConstraints);
        }

        if (!isPointType) {
            org.openide.awt.Mnemonics.setLocalizedText(
                lblGebeaudeGesamt,
                org.openide.util.NbBundle.getMessage(
                    NasFeePreviewPanel.class,
                    "NasFeePreviewPanel.lblGebeaudeGesamt.text")); // NOI18N
        }
        if (!isPointType) {
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = 3;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
            gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
            add(lblGebeaudeGesamt, gridBagConstraints);
        }

        if (isPointType) {
            org.openide.awt.Mnemonics.setLocalizedText(
                lblPunkteAnzahl,
                org.openide.util.NbBundle.getMessage(
                    NasFeePreviewPanel.class,
                    "NasFeePreviewPanel.lblPunkteAnzahl.text")); // NOI18N
        }
        if (isPointType) {
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = 4;
            gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
            add(lblPunkteAnzahl, gridBagConstraints);
        }

        if (isPointType) {
            org.openide.awt.Mnemonics.setLocalizedText(
                lblPunkteGesamt,
                org.openide.util.NbBundle.getMessage(
                    NasFeePreviewPanel.class,
                    "NasFeePreviewPanel.lblPunkteGesamt.text")); // NOI18N
        }
        if (isPointType) {
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 2;
            gridBagConstraints.gridy = 4;
            gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
            gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
            add(lblPunkteGesamt, gridBagConstraints);
        }

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblGesamtValue.setFont(new java.awt.Font("DejaVu Sans", 1, 14));                                               // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            lblGesamtValue,
            org.openide.util.NbBundle.getMessage(NasFeePreviewPanel.class, "NasFeePreviewPanel.lblGesamtValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 0);
        jPanel1.add(lblGesamtValue, gridBagConstraints);

        lblGesamt.setFont(new java.awt.Font("DejaVu Sans", 1, 14));                                               // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(
            lblGesamt,
            org.openide.util.NbBundle.getMessage(NasFeePreviewPanel.class, "NasFeePreviewPanel.lblGesamt.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        jPanel1.add(lblGesamt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jPanel1, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents
}
