/*
 * CoolThemaRenderer.java
 *
 * Created on 10. November 3508, 11:56
 */
package de.cismet.cids.custom.objecteditors.wunda_blau;

import de.cismet.cids.annotations.AggregationRenderer;
import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.dynamics.CidsBeanStore;
import de.cismet.tools.gui.DoNotWrap;
import de.cismet.tools.gui.PureCoolPanel;
import de.cismet.tools.gui.TitleComponentProvider;
import javax.swing.JComponent;

/**
 * de.cismet.cids.objectrenderer.CoolThemaRenderer
 *
 * Renderer for the "Thema"-theme
 *
 * @author srichter
 */
@AggregationRenderer
public class Alb_baulastblattEditor extends PureCoolPanel implements DoNotWrap, CidsBeanStore, TitleComponentProvider {

    static final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(Alb_baulastblattEditor.class);
    private final boolean editable;
    private CidsBean cidsBean;
    public static final String TITLE_PREFIX = "Baulast";
    public static final String TITLE_AGR_PREFIX = "Baulasten";

    /** Creates new form CoolThemaRenderer */
    public Alb_baulastblattEditor(final boolean editable) {
        this.editable = editable;
        initComponents();

    }

    @Override
    public CidsBean getCidsBean() {
        return cidsBean;
    }

    @Override
    public void setCidsBean(final CidsBean cidsBean) {
        if (cidsBean != null) {
            this.cidsBean = cidsBean;
            bindingGroup.unbind();
            bindingGroup.bind();
        }
    }

    /** Creates new form CoolThemaRenderer */
    public Alb_baulastblattEditor() {
        this(true);
    }

    /**
     * 
     * @return true if the fields/boxes are editable
     */
    public boolean isEditable() {
        return editable;
    }

    /**
     *
     * @return a ThemaBean which encapsulates all the information for this theme
     * from the GUI.
     */
//    public ThemaBean getContent() {
//        final ThemaBean.Builder builder = ThemaBean.builder();
//        builder.aenderungsdatum(new Date(System.currentTimeMillis())).aktAggregierenderObjektRenderer(chkAktAggObjektRenderer.isSelected()).aktAnsprechpartnerImplementierung(evalCB(cbAktImplementierung)).aktAnsprechpartnerSpezifizierung(evalCB(cbAktAnspSpezif)).aktEditoren(chkAktEditor.isSelected()).aktFeatureRenderer(chkAktFeatureRenderer.isSelected()).aktGeometrieModell(evalCB(cbAktGeometriemodell)).aktKategorie(evalCB(cbAktKategorie)).aktObjektRenderer(chkAktObjektRenderer.isSelected()).aktRealisierungsstand(evalCB(cbAktRealisierung)).aktReportTemplates(chkAktReportTemplates.isSelected()).aktSpezifischesSuchen(chkAktSpezSuchen.isSelected()).aktWartungsvertrag(evalCB(cbAktWartung)).ansprechpartner(txtAnsprechpartner.getText()).bemerkungen(txtBemerkung.getText()).bezeichnung(txtBezeichnung.getText()).fachthema(chkFachthema.isSelected()).fachverfahren(chkFachverfahren.isSelected()).gazDienst(evalCB(cbDienst)).gazGeoportalGUI(chkGeoPortal.isSelected()).gazLocationtypes(txtLocationtypes.getText()).gazWundaGUI(chkWundaGui.isSelected()).inhalt(txtInhalt.getText()).letzteAenderungDurch(evalCB(cbLetzteAktualisierung)).nutzerzahl(txtNutzerzahl.getText()).nutzungsart(evalCB(cbNutzungsart)).organisationseinheit(txtOrganisationseinheit.getText()).wmsDatenbereitstellung(evalCB(cbDatenbereitstellung)).wmsDatenquelle(evalCB(cbDatenquelle)).wmsKaskadiertAufSims(chkKaskadiert.isSelected()).wmsPubliziertImGeoportal(chkPubliziert.isSelected()).wmsWms(evalCB(cbWMS)).zukAggregierenderObjektRenderer(chkZukAggObjektRenderer.isSelected()).zukAnsprechpartnerImplementierung(evalCB(cbZukImplementierung)).zukAnsprechpartnerSpezifizierung(evalCB(cbZukAnspSpezif)).zukEditoren(chkZukEditor.isSelected()).zukFeatureRenderer(chkZukFeatureRenderer.isSelected()).zukGeometrieModell(evalCB(cbZukGeometriemodell)).zukKategorie(evalCB(cbZukKategorie)).zukObjektRenderer(chkZukObjektRenderer.isSelected()).zukRealisierungsstand(evalCB(cbZukRealisierung)).zukReportTemplates(chkZukReportTemplates.isSelected()).zukSpezifischesSuchen(chkZukSpezSuchen.isSelected()).zukWartungsvertrag(evalCB(cbZukWartung));
//        return builder.build();
//    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        sqlDateToUtilDateConverter = new de.cismet.cids.editors.converters.SqlDateToUtilDateConverter();
        panTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panMain = new javax.swing.JPanel();
        alb_baulastEditorPanel1 = new de.cismet.cids.custom.objecteditors.wunda_blau.Alb_baulastEditorPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        panTitle.setOpaque(false);
        panTitle.setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14));
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Baulastblatt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panTitle.add(lblTitle, gridBagConstraints);

        setLayout(new java.awt.BorderLayout());

        panMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panMain.setOpaque(false);
        panMain.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panMain.add(alb_baulastEditorPanel1, gridBagConstraints);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${cidsBean.baulasten}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jList1);
        bindingGroup.addBinding(jListBinding);

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panMain.add(jScrollPane1, gridBagConstraints);

        add(panMain, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged
    /**
     * Move-backward button action
     *
     * @param evt
     */
    /**
     * Move forward button action
     * @param evt
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.cids.custom.objecteditors.wunda_blau.Alb_baulastEditorPanel alb_baulastEditorPanel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panMain;
    private javax.swing.JPanel panTitle;
    private de.cismet.cids.editors.converters.SqlDateToUtilDateConverter sqlDateToUtilDateConverter;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public JComponent getTitleComponent() {
        return panTitle;
    }
}
