/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Alb_baulastEditorPanel.java
 *
 * Created on 27.11.2009, 14:20:31
 */
package de.cismet.cids.custom.objecteditors.wunda_blau;

import de.cismet.cids.custom.objectrenderer.utils.ObjectRendererUIUtils;
import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.editors.DefaultBindableDateChooser;
import de.cismet.tools.collections.TypeSafeCollections;
import java.util.Collection;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author srichter
 */
public class Alb_baulastEditorPanel extends javax.swing.JPanel {

    private CidsBean cidsBean;
    private final boolean editable;
    private final Collection<JComponent> editableComponents;

    /** Creates new form Alb_baulastEditorPanel */
    public Alb_baulastEditorPanel(boolean editable) {
        this.editable = editable;
        this.editableComponents = TypeSafeCollections.newArrayList();
        initComponents();
        initEditableComponents();
    }

    private final void initEditableComponents() {
        editableComponents.add(txtLageplan);
        editableComponents.add(txtLaufendeNr);
        editableComponents.add(txtTextblatt);
        editableComponents.add(defaultBindableDateChooser1);
        editableComponents.add(defaultBindableDateChooser2);
        editableComponents.add(defaultBindableDateChooser3);
        editableComponents.add(defaultBindableDateChooser4);
        editableComponents.add(lstFlurstueckeBeguenstigt);
        editableComponents.add(lstFlurstueckeBelastet);
        for (final JComponent editableComponent : editableComponents) {
            editableComponent.setOpaque(editable);
            if (!editable) {
                editableComponent.setBorder(null);
                if (editableComponent instanceof JTextField) {
                    ((JTextField) editableComponent).setEditable(false);
                } else if (editableComponent instanceof DefaultBindableDateChooser) {
                    ((DefaultBindableDateChooser) editableComponent).setEditable(false);
                } else if (editableComponent instanceof JList) {
                    JList listEC = ((JList) editableComponent);
                    listEC.setEnabled(false);
                }
                panControlsFSBeg.setVisible(false);
                panControlsFSBel.setVisible(false);
            }
        }
    }

    /** Creates new form Alb_baulastEditorPanel */
    public Alb_baulastEditorPanel() {
        this(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        sqlDateToUtilDateConverter = new de.cismet.cids.editors.converters.SqlDateToUtilDateConverter();
        panMain = new javax.swing.JPanel();
        rpFSBeguenstigt = new de.cismet.tools.gui.RoundedPanel();
        scpFlurstueckeBeguenstigt = new javax.swing.JScrollPane();
        lstFlurstueckeBeguenstigt = new javax.swing.JList();
        semiRoundedPanel1 = new de.cismet.tools.gui.SemiRoundedPanel();
        lblHeadBegFlurstuecke = new javax.swing.JLabel();
        panControlsFSBeg = new javax.swing.JPanel();
        btnAddBeguenstigt = new javax.swing.JButton();
        btnRemoveBeguenstigt = new javax.swing.JButton();
        rpFSBelastet = new de.cismet.tools.gui.RoundedPanel();
        scpFlurstueckeBelastet = new javax.swing.JScrollPane();
        lstFlurstueckeBelastet = new javax.swing.JList();
        semiRoundedPanel2 = new de.cismet.tools.gui.SemiRoundedPanel();
        lblHeadBelFlurstuecke = new javax.swing.JLabel();
        panControlsFSBel = new javax.swing.JPanel();
        btnAddBelastet = new javax.swing.JButton();
        btnRemoveBelastet = new javax.swing.JButton();
        rpInfo = new de.cismet.tools.gui.RoundedPanel();
        lblDescLaufendeNr = new javax.swing.JLabel();
        lblDescEintragungsdatum = new javax.swing.JLabel();
        lblDescBefristungsdatum = new javax.swing.JLabel();
        lblDescGeschlossenAm = new javax.swing.JLabel();
        lblDescLoeschungsdatum = new javax.swing.JLabel();
        lblDescTextblatt = new javax.swing.JLabel();
        txtTextblatt = new javax.swing.JTextField();
        txtLaufendeNr = new javax.swing.JTextField();
        lblDescLageplan = new javax.swing.JLabel();
        txtLageplan = new javax.swing.JTextField();
        defaultBindableDateChooser4 = new de.cismet.cids.editors.DefaultBindableDateChooser();
        defaultBindableDateChooser1 = new de.cismet.cids.editors.DefaultBindableDateChooser();
        defaultBindableDateChooser2 = new de.cismet.cids.editors.DefaultBindableDateChooser();
        defaultBindableDateChooser3 = new de.cismet.cids.editors.DefaultBindableDateChooser();
        rpHeadInfo = new de.cismet.tools.gui.SemiRoundedPanel();
        lblHeadInfo = new javax.swing.JLabel();

        setOpaque(false);

        panMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panMain.setOpaque(false);
        panMain.setLayout(new java.awt.GridBagLayout());

        scpFlurstueckeBeguenstigt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createEtchedBorder()));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${cidsBean.flurstuecke_beguenstigt}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, lstFlurstueckeBeguenstigt);
        bindingGroup.addBinding(jListBinding);

        scpFlurstueckeBeguenstigt.setViewportView(lstFlurstueckeBeguenstigt);

        rpFSBeguenstigt.add(scpFlurstueckeBeguenstigt, java.awt.BorderLayout.CENTER);

        semiRoundedPanel1.setBackground(java.awt.Color.darkGray);
        semiRoundedPanel1.setLayout(new java.awt.GridBagLayout());

        lblHeadBegFlurstuecke.setForeground(new java.awt.Color(255, 255, 255));
        lblHeadBegFlurstuecke.setText("Begünstigte Flurstücke");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        semiRoundedPanel1.add(lblHeadBegFlurstuecke, gridBagConstraints);

        rpFSBeguenstigt.add(semiRoundedPanel1, java.awt.BorderLayout.NORTH);

        panControlsFSBeg.setOpaque(false);
        panControlsFSBeg.setLayout(new java.awt.GridBagLayout());

        btnAddBeguenstigt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/objecteditors/wunda_blau/edit_add_mini.png"))); // NOI18N
        btnAddBeguenstigt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBeguenstigtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panControlsFSBeg.add(btnAddBeguenstigt, gridBagConstraints);

        btnRemoveBeguenstigt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/objecteditors/wunda_blau/edit_remove_mini.png"))); // NOI18N
        btnRemoveBeguenstigt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveBeguenstigtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panControlsFSBeg.add(btnRemoveBeguenstigt, gridBagConstraints);

        rpFSBeguenstigt.add(panControlsFSBeg, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panMain.add(rpFSBeguenstigt, gridBagConstraints);

        scpFlurstueckeBelastet.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createEtchedBorder()));

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${cidsBean.flurstuecke_beguenstigt}");
        jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, lstFlurstueckeBelastet);
        bindingGroup.addBinding(jListBinding);

        scpFlurstueckeBelastet.setViewportView(lstFlurstueckeBelastet);

        rpFSBelastet.add(scpFlurstueckeBelastet, java.awt.BorderLayout.CENTER);

        semiRoundedPanel2.setBackground(java.awt.Color.darkGray);
        semiRoundedPanel2.setLayout(new java.awt.GridBagLayout());

        lblHeadBelFlurstuecke.setForeground(new java.awt.Color(255, 255, 255));
        lblHeadBelFlurstuecke.setText("Belastete Flurstücke");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        semiRoundedPanel2.add(lblHeadBelFlurstuecke, gridBagConstraints);

        rpFSBelastet.add(semiRoundedPanel2, java.awt.BorderLayout.NORTH);

        panControlsFSBel.setOpaque(false);
        panControlsFSBel.setLayout(new java.awt.GridBagLayout());

        btnAddBelastet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/objecteditors/wunda_blau/edit_add_mini.png"))); // NOI18N
        btnAddBelastet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBelastetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panControlsFSBel.add(btnAddBelastet, gridBagConstraints);

        btnRemoveBelastet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/objecteditors/wunda_blau/edit_remove_mini.png"))); // NOI18N
        btnRemoveBelastet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveBelastetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panControlsFSBel.add(btnRemoveBelastet, gridBagConstraints);

        rpFSBelastet.add(panControlsFSBel, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panMain.add(rpFSBelastet, gridBagConstraints);

        rpInfo.setLayout(new java.awt.GridBagLayout());

        lblDescLaufendeNr.setText("Laufende Nummer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(lblDescLaufendeNr, gridBagConstraints);

        lblDescEintragungsdatum.setText("Eintragungsdatum:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(lblDescEintragungsdatum, gridBagConstraints);

        lblDescBefristungsdatum.setText("Befristungsdatum:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(lblDescBefristungsdatum, gridBagConstraints);

        lblDescGeschlossenAm.setText("Geschlossen am:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(lblDescGeschlossenAm, gridBagConstraints);

        lblDescLoeschungsdatum.setText("Löschungsdatum:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(lblDescLoeschungsdatum, gridBagConstraints);

        lblDescTextblatt.setText("Textblatt:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(lblDescTextblatt, gridBagConstraints);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.textblatt.object_name}"), txtTextblatt, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("nicht verfügbar");
        binding.setSourceUnreadableValue("<Error>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        rpInfo.add(txtTextblatt, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.laufende_nummer}"), txtLaufendeNr, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("nicht verfügbar");
        binding.setSourceUnreadableValue("<Error>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        rpInfo.add(txtLaufendeNr, gridBagConstraints);

        lblDescLageplan.setText("Lageplan:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(lblDescLageplan, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.lageplan.object_name}"), txtLageplan, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("nicht verfügbar");
        binding.setSourceUnreadableValue("<Error>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(txtLageplan, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.loeschungsdatum}"), defaultBindableDateChooser4, org.jdesktop.beansbinding.BeanProperty.create("date"));
        binding.setSourceNullValue(null);
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(defaultBindableDateChooser4, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.eintragungsdatum}"), defaultBindableDateChooser1, org.jdesktop.beansbinding.BeanProperty.create("date"));
        binding.setSourceNullValue(null);
        binding.setSourceUnreadableValue(null);
        binding.setConverter(sqlDateToUtilDateConverter);
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(defaultBindableDateChooser1, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.befristungsdatum}"), defaultBindableDateChooser2, org.jdesktop.beansbinding.BeanProperty.create("date"));
        binding.setSourceNullValue(null);
        binding.setSourceUnreadableValue(null);
        binding.setConverter(sqlDateToUtilDateConverter);
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(defaultBindableDateChooser2, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.geschlossen_am}"), defaultBindableDateChooser3, org.jdesktop.beansbinding.BeanProperty.create("date"));
        binding.setSourceNullValue(null);
        binding.setSourceUnreadableValue(null);
        binding.setConverter(sqlDateToUtilDateConverter);
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpInfo.add(defaultBindableDateChooser3, gridBagConstraints);

        rpHeadInfo.setBackground(java.awt.Color.darkGray);
        rpHeadInfo.setLayout(new java.awt.GridBagLayout());

        lblHeadInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblHeadInfo.setText("Info");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rpHeadInfo.add(lblHeadInfo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        rpInfo.add(rpHeadInfo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panMain.add(rpInfo, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panMain, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBelastetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBelastetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddBelastetActionPerformed

    private void btnAddBeguenstigtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBeguenstigtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddBeguenstigtActionPerformed

    private void btnRemoveBeguenstigtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBeguenstigtActionPerformed
        final Object[] selection = lstFlurstueckeBeguenstigt.getSelectedValues();
        if (selection != null) {
            final int answer = JOptionPane.showConfirmDialog(this, "Soll das Flurstueck wirklich gelöscht werden?", "Suchwort entfernen", JOptionPane.YES_NO_OPTION);
            if (answer == JOptionPane.YES_OPTION) {
                final Object possibleFSCol = cidsBean.getProperty("flurstuecke_beguenstigt");
                if (possibleFSCol instanceof Collection) {
                    final Collection flurstueckCol = (Collection) possibleFSCol;
                    for (Object cur : selection) {
                        try {
                            flurstueckCol.remove(cur);
                        } catch (Exception e) {
                            ObjectRendererUIUtils.showExceptionWindowToUser("Fehler beim Löschen", e, this);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRemoveBeguenstigtActionPerformed

    private void btnRemoveBelastetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBelastetActionPerformed
        final Object[] selection = lstFlurstueckeBeguenstigt.getSelectedValues();
        if (selection != null) {
            final int answer = JOptionPane.showConfirmDialog(this, "Soll das Flurstueck wirklich gelöscht werden?", "Suchwort entfernen", JOptionPane.YES_NO_OPTION);
            if (answer == JOptionPane.YES_OPTION) {
                final Object possibleFSCol = cidsBean.getProperty("flurstuecke_belastet");
                if (possibleFSCol instanceof Collection) {
                    final Collection flurstueckCol = (Collection) possibleFSCol;
                    for (Object cur : selection) {
                        try {
                            flurstueckCol.remove(cur);
                        } catch (Exception e) {
                            ObjectRendererUIUtils.showExceptionWindowToUser("Fehler beim Löschen", e, this);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRemoveBelastetActionPerformed

    public CidsBean getCidsBean() {
        return cidsBean;
    }

    public void setCidsBean(CidsBean cidsBean) {
        if (cidsBean != null) {
            this.cidsBean = cidsBean;
            bindingGroup.unbind();
            bindingGroup.bind();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBeguenstigt;
    private javax.swing.JButton btnAddBelastet;
    private javax.swing.JButton btnRemoveBeguenstigt;
    private javax.swing.JButton btnRemoveBelastet;
    private de.cismet.cids.editors.DefaultBindableDateChooser defaultBindableDateChooser1;
    private de.cismet.cids.editors.DefaultBindableDateChooser defaultBindableDateChooser2;
    private de.cismet.cids.editors.DefaultBindableDateChooser defaultBindableDateChooser3;
    private de.cismet.cids.editors.DefaultBindableDateChooser defaultBindableDateChooser4;
    private javax.swing.JLabel lblDescBefristungsdatum;
    private javax.swing.JLabel lblDescEintragungsdatum;
    private javax.swing.JLabel lblDescGeschlossenAm;
    private javax.swing.JLabel lblDescLageplan;
    private javax.swing.JLabel lblDescLaufendeNr;
    private javax.swing.JLabel lblDescLoeschungsdatum;
    private javax.swing.JLabel lblDescTextblatt;
    private javax.swing.JLabel lblHeadBegFlurstuecke;
    private javax.swing.JLabel lblHeadBelFlurstuecke;
    private javax.swing.JLabel lblHeadInfo;
    private javax.swing.JList lstFlurstueckeBeguenstigt;
    private javax.swing.JList lstFlurstueckeBelastet;
    private javax.swing.JPanel panControlsFSBeg;
    private javax.swing.JPanel panControlsFSBel;
    private javax.swing.JPanel panMain;
    private de.cismet.tools.gui.RoundedPanel rpFSBeguenstigt;
    private de.cismet.tools.gui.RoundedPanel rpFSBelastet;
    private de.cismet.tools.gui.SemiRoundedPanel rpHeadInfo;
    private de.cismet.tools.gui.RoundedPanel rpInfo;
    private javax.swing.JScrollPane scpFlurstueckeBeguenstigt;
    private javax.swing.JScrollPane scpFlurstueckeBelastet;
    private de.cismet.tools.gui.SemiRoundedPanel semiRoundedPanel1;
    private de.cismet.tools.gui.SemiRoundedPanel semiRoundedPanel2;
    private de.cismet.cids.editors.converters.SqlDateToUtilDateConverter sqlDateToUtilDateConverter;
    private javax.swing.JTextField txtLageplan;
    private javax.swing.JTextField txtLaufendeNr;
    private javax.swing.JTextField txtTextblatt;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
