/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * CoolThemaRenderer.java
 *
 * Created on 10. November 3508, 11:56
 */
package de.cismet.cids.custom.objecteditors.wunda_blau;

import Sirius.navigator.ui.RequestsFullSizeComponent;

import org.apache.log4j.Logger;

import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.Converter;
import org.jdesktop.beansbinding.ELProperty;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

import de.cismet.cids.client.tools.DevelopmentTools;

import de.cismet.cids.custom.objecteditors.wunda_blau.albo.AlboFlaecheArbeitsstandPanel;
import de.cismet.cids.custom.objecteditors.wunda_blau.albo.AlboFlaecheBemerkungenPanel;
import de.cismet.cids.custom.objecteditors.wunda_blau.albo.AlboFlaecheMainPanel;
import de.cismet.cids.custom.objecteditors.wunda_blau.albo.AlboFlaecheMassnahmenPanel;

import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.dynamics.DisposableCidsBeanStore;

import de.cismet.cids.editors.DefaultCustomObjectEditor;
import de.cismet.cids.editors.EditorClosedEvent;
import de.cismet.cids.editors.EditorSaveListener;

import de.cismet.cids.tools.metaobjectrenderer.CidsBeanRenderer;

import de.cismet.cismap.commons.gui.MappingComponent;
import de.cismet.cismap.commons.interaction.CismapBroker;

import de.cismet.connectioncontext.ConnectionContext;
import de.cismet.connectioncontext.ConnectionContextStore;

import de.cismet.tools.gui.BorderProvider;
import de.cismet.tools.gui.FooterComponentProvider;
import de.cismet.tools.gui.TitleComponentProvider;
import de.cismet.tools.gui.log4jquickconfig.Log4JQuickConfig;

/**
 * DOCUMENT ME!
 *
 * @version  $Revision$, $Date$
 */
public class AlboFlaecheEditor extends JPanel implements CidsBeanRenderer,
    DisposableCidsBeanStore,
    TitleComponentProvider,
    FooterComponentProvider,
    BorderProvider,
    RequestsFullSizeComponent,
    EditorSaveListener,
    ConnectionContextStore {

    //~ Static fields/initializers ---------------------------------------------

    private static final Logger LOG = Logger.getLogger(AlboFlaecheEditor.class);
    public static Converter<String, String> DATE_TO_STRING = null;

    /**
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;
        bindingGroup = new BindingGroup();

        panTitle = new JPanel();
        lblTitle = new JLabel();
        panFooter = new JPanel();
        filler65 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(32767, 0));
        panButtons = new JPanel();
        jToggleButton1 = new JToggleButton();
        jToggleButton2 = new JToggleButton();
        jToggleButton3 = new JToggleButton();
        jToggleButton4 = new JToggleButton();
        jToggleButton5 = new JToggleButton();
        filler66 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(32767, 0));
        buttonGroup1 = new ButtonGroup();
        panMainCard = new JPanel();
        panCardFlaeche = new JPanel();
        panMain = new AlboFlaecheMainPanel(isEditable());
        panCardMassnahmen = new JPanel();
        panMassnahmen = new AlboFlaecheMassnahmenPanel(isEditable());
        panCardArbeitsstand = new JPanel();
        panArbeitsstand = new AlboFlaecheArbeitsstandPanel(isEditable());
        panCardBemerkung = new JPanel();
        panBemerkungen = new AlboFlaecheBemerkungenPanel(isEditable());
        panCardAktionen = new JPanel();
        filler74 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(0, 32767));
        filler73 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(0, 32767));
        jButton7 = new JButton();
        jButton8 = new JButton();
        jButton17 = new JButton();
        jButton18 = new JButton();

        final FormListener formListener = new FormListener();

        panTitle.setName("panTitle"); // NOI18N
        panTitle.setOpaque(false);
        panTitle.setLayout(new GridBagLayout());

        lblTitle.setForeground(new Color(255, 255, 255));
        lblTitle.setName("lblTitle"); // NOI18N

        final Binding binding = Bindings.createAutoBinding(
                AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                ELProperty.create(
                    "<html><body><h2><nobr>Altlastenkataster - Erhebungsnummer: ${cidsBean.erhebungsnummer}"),
                lblTitle,
                BeanProperty.create("text"));
        binding.setSourceNullValue("<html><body><h2><nobr>Altlastenkataster - Erhebungsnummer: -");
        binding.setSourceUnreadableValue("<html><body><h2><nobr>Altlastenkataster - Erhebungsnummer: <i>[Fehler]");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        panTitle.add(lblTitle, gridBagConstraints);

        panFooter.setName("panFooter"); // NOI18N
        panFooter.setOpaque(false);
        panFooter.setLayout(new GridBagLayout());

        filler65.setName("filler65"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panFooter.add(filler65, gridBagConstraints);

        panButtons.setBorder(BorderFactory.createEmptyBorder(0, 0, 6, 0));
        panButtons.setName("panButtons"); // NOI18N
        panButtons.setOpaque(false);
        panButtons.setLayout(new GridLayout(1, 0, 10, 0));

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setText("Fläche");
        jToggleButton1.setName("jToggleButton1"); // NOI18N
        jToggleButton1.addActionListener(formListener);
        panButtons.add(jToggleButton1);

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setText("Arbeitsstand");
        jToggleButton2.setName("jToggleButton2"); // NOI18N
        jToggleButton2.addActionListener(formListener);
        panButtons.add(jToggleButton2);

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("Maßnahmen");
        jToggleButton3.setName("jToggleButton3"); // NOI18N
        jToggleButton3.addActionListener(formListener);
        panButtons.add(jToggleButton3);

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setText("Bemerkung");
        jToggleButton4.setName("jToggleButton4"); // NOI18N
        jToggleButton4.addActionListener(formListener);
        panButtons.add(jToggleButton4);

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setText("Aktionen");
        jToggleButton5.setName("jToggleButton5"); // NOI18N
        jToggleButton5.addActionListener(formListener);
        panButtons.add(jToggleButton5);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        panFooter.add(panButtons, gridBagConstraints);

        filler66.setName("filler66"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panFooter.add(filler66, gridBagConstraints);

        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new GridBagLayout());

        panMainCard.setName("panMainCard"); // NOI18N
        panMainCard.setOpaque(false);
        panMainCard.setLayout(new CardLayout());

        panCardFlaeche.setName("panCardFlaeche"); // NOI18N
        panCardFlaeche.setOpaque(false);
        panCardFlaeche.setLayout(new BorderLayout());

        panMain.setName("panMain"); // NOI18N
        panCardFlaeche.add(panMain, BorderLayout.CENTER);

        panMainCard.add(panCardFlaeche, "flaeche");

        panCardMassnahmen.setName("panCardMassnahmen"); // NOI18N
        panCardMassnahmen.setOpaque(false);
        panCardMassnahmen.setLayout(new BorderLayout());

        panMassnahmen.setName("panMassnahmen"); // NOI18N
        panCardMassnahmen.add(panMassnahmen, BorderLayout.CENTER);

        panMainCard.add(panCardMassnahmen, "massnahmen");

        panCardArbeitsstand.setName("panCardArbeitsstand"); // NOI18N
        panCardArbeitsstand.setOpaque(false);
        panCardArbeitsstand.setLayout(new BorderLayout());

        panArbeitsstand.setName("panArbeitsstand"); // NOI18N
        panCardArbeitsstand.add(panArbeitsstand, BorderLayout.CENTER);

        panMainCard.add(panCardArbeitsstand, "arbeitsstand");

        panCardBemerkung.setName("panCardBemerkung"); // NOI18N
        panCardBemerkung.setOpaque(false);
        panCardBemerkung.setLayout(new BorderLayout());

        panBemerkungen.setName("panBemerkungen"); // NOI18N
        panCardBemerkung.add(panBemerkungen, BorderLayout.CENTER);

        panMainCard.add(panCardBemerkung, "bemerkung");

        panCardAktionen.setName("panCardAktionen"); // NOI18N
        panCardAktionen.setOpaque(false);
        panCardAktionen.setLayout(new GridBagLayout());

        filler74.setName("filler74"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 99;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        panCardAktionen.add(filler74, gridBagConstraints);

        filler73.setName("filler73"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        panCardAktionen.add(filler73, gridBagConstraints);

        jButton7.setText("Neue Landesregistriern-Nummer");
        jButton7.setName("jButton7"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(10, 0, 10, 0);
        panCardAktionen.add(jButton7, gridBagConstraints);

        jButton8.setText("Gesamtfläche <-> Teilfäche");
        jButton8.setName("jButton8"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(10, 0, 10, 0);
        panCardAktionen.add(jButton8, gridBagConstraints);

        jButton17.setText("Flächenart ändern");
        jButton17.setName("jButton17"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(10, 0, 10, 0);
        panCardAktionen.add(jButton17, gridBagConstraints);

        jButton18.setText("Export");
        jButton18.setName("jButton18"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(10, 0, 10, 0);
        panCardAktionen.add(jButton18, gridBagConstraints);

        panMainCard.add(panCardAktionen, "aktionen");

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(10, 10, 10, 10);
        add(panMainCard, gridBagConstraints);

        bindingGroup.bind();
    }

    /**
     * Code for dispatching events from components to event handlers.
     *
     * @version  $Revision$, $Date$
     */
    private class FormListener implements ActionListener {

        /**
         * Creates a new FormListener object.
         */
        FormListener() {
        }

        @Override
        public void actionPerformed(final ActionEvent evt) {
            if (evt.getSource() == jToggleButton1) {
                AlboFlaecheEditor.this.jToggleButton1ActionPerformed(evt);
            } else if (evt.getSource() == jToggleButton2) {
                AlboFlaecheEditor.this.jToggleButton2ActionPerformed(evt);
            } else if (evt.getSource() == jToggleButton3) {
                AlboFlaecheEditor.this.jToggleButton3ActionPerformed(evt);
            } else if (evt.getSource() == jToggleButton4) {
                AlboFlaecheEditor.this.jToggleButton4ActionPerformed(evt);
            } else if (evt.getSource() == jToggleButton5) {
                AlboFlaecheEditor.this.jToggleButton5ActionPerformed(evt);
            }
        }
    } // </editor-fold>//GEN-END:initComponents

    //~ Instance fields --------------------------------------------------------

    private final boolean editable;
    private CidsBean cidsBean;

    private ConnectionContext connectionContext = ConnectionContext.createDummy();
    private CardLayout cardLayout;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private Box.Filler filler65;
    private Box.Filler filler66;
    private Box.Filler filler73;
    private Box.Filler filler74;
    private JButton jButton17;
    private JButton jButton18;
    private JButton jButton7;
    private JButton jButton8;
    private JToggleButton jToggleButton1;
    private JToggleButton jToggleButton2;
    private JToggleButton jToggleButton3;
    private JToggleButton jToggleButton4;
    private JToggleButton jToggleButton5;
    private JLabel lblTitle;
    private AlboFlaecheArbeitsstandPanel panArbeitsstand;
    private AlboFlaecheBemerkungenPanel panBemerkungen;
    private JPanel panButtons;
    private JPanel panCardAktionen;
    private JPanel panCardArbeitsstand;
    private JPanel panCardBemerkung;
    private JPanel panCardFlaeche;
    private JPanel panCardMassnahmen;
    private JPanel panFooter;
    private AlboFlaecheMainPanel panMain;
    private JPanel panMainCard;
    private AlboFlaecheMassnahmenPanel panMassnahmen;
    private JPanel panTitle;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new AlboFlaecheEditor object.
     */
    public AlboFlaecheEditor() {
        this(true);
    }

    /**
     * Creates a new AlboFlaecheEditor object.
     *
     * @param  editable  DOCUMENT ME!
     */
    public AlboFlaecheEditor(final boolean editable) {
        this.editable = editable;
    }

    //~ Methods ----------------------------------------------------------------

    @Override
    public final void initWithConnectionContext(final ConnectionContext connectionContext) {
        this.connectionContext = connectionContext;
        initComponents();

        panMain.initWithConnectionContext(connectionContext);
        panArbeitsstand.initWithConnectionContext(connectionContext);
        panMassnahmen.initWithConnectionContext(connectionContext);
        panBemerkungen.initWithConnectionContext(connectionContext);

        this.cardLayout = (CardLayout)panMainCard.getLayout();
    }

    @Override
    public final ConnectionContext getConnectionContext() {
        return connectionContext;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public CidsBean getCidsBean() {
        return cidsBean;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  cidsBean  DOCUMENT ME!
     */
    @Override
    public void setCidsBean(final CidsBean cidsBean) {
        try {
            bindingGroup.unbind();
        } catch (final Exception ex) {
        }

        if (cidsBean != null) {
            if (isEditable()) {
                if (cidsBean.getProperty("fk_massnahme") == null) {
                    try {
                        cidsBean.setProperty(
                            "fk_massnahme",
                            CidsBean.getMetaClassFromTableName("WUNDA_BLAU", "ALBO_MASSNAHME", getConnectionContext())
                                        .getEmptyInstance(getConnectionContext()).getBean());
                    } catch (final Exception ex) {
                        LOG.fatal(ex, ex);
                    }
                }
                if (cidsBean.getProperty("fk_massnahme_dekontamination") == null) {
                    try {
                        cidsBean.setProperty(
                            "fk_massnahme_dekontamination",
                            CidsBean.getMetaClassFromTableName(
                                "WUNDA_BLAU",
                                "ALBO_MASSNAHME_DEKONTAMINATION",
                                getConnectionContext()).getEmptyInstance(getConnectionContext()).getBean());
                    } catch (final Exception ex) {
                        LOG.fatal(ex, ex);
                    }
                }
                if (cidsBean.getProperty("fk_massnahme_sicherung") == null) {
                    try {
                        cidsBean.setProperty(
                            "fk_massnahme_sicherung",
                            CidsBean.getMetaClassFromTableName(
                                "WUNDA_BLAU",
                                "ALBO_MASSNAHME_SICHERUNG",
                                getConnectionContext()).getEmptyInstance(getConnectionContext()).getBean());
                    } catch (final Exception ex) {
                        LOG.fatal(ex, ex);
                    }
                }
                if (cidsBean.getProperty("fk_massnahme_schutzbeschraenkung") == null) {
                    try {
                        cidsBean.setProperty(
                            "fk_massnahme_schutzbeschraenkung",
                            CidsBean.getMetaClassFromTableName(
                                "WUNDA_BLAU",
                                "ALBO_MASSNAHME_SCHUTZBESCHRAENKUNG",
                                getConnectionContext()).getEmptyInstance(getConnectionContext()).getBean());
                    } catch (final Exception ex) {
                        LOG.fatal(ex, ex);
                    }
                }
            }

            DefaultCustomObjectEditor.setMetaClassInformationToMetaClassStoreComponentsInBindingGroup(
                bindingGroup,
                cidsBean,
                getConnectionContext());
            this.cidsBean = cidsBean;
            bindingGroup.bind();
        }
        panMain.setCidsBean(cidsBean);
        panArbeitsstand.setCidsBean(cidsBean);
        panMassnahmen.setCidsBean(cidsBean);
        panBemerkungen.setCidsBean(cidsBean);
    }

    /**
     * DOCUMENT ME!
     *
     * @return  true if the fields/boxes are editable
     */
    public boolean isEditable() {
        return editable;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jToggleButton1ActionPerformed(final ActionEvent evt) { //GEN-FIRST:event_jToggleButton1ActionPerformed
        cardLayout.show(panMainCard, "flaeche");
    }                                                                   //GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jToggleButton2ActionPerformed(final ActionEvent evt) { //GEN-FIRST:event_jToggleButton2ActionPerformed
        cardLayout.show(panMainCard, "arbeitsstand");
    }                                                                   //GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jToggleButton3ActionPerformed(final ActionEvent evt) { //GEN-FIRST:event_jToggleButton3ActionPerformed
        cardLayout.show(panMainCard, "massnahmen");
    }                                                                   //GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jToggleButton4ActionPerformed(final ActionEvent evt) { //GEN-FIRST:event_jToggleButton4ActionPerformed
        cardLayout.show(panMainCard, "bemerkung");
    }                                                                   //GEN-LAST:event_jToggleButton4ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jToggleButton5ActionPerformed(final ActionEvent evt) { //GEN-FIRST:event_jToggleButton5ActionPerformed
        cardLayout.show(panMainCard, "aktionen");
    }                                                                   //GEN-LAST:event_jToggleButton5ActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public JComponent getTitleComponent() {
        return panTitle;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public JComponent getFooterComponent() {
        return panFooter;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public Border getTitleBorder() {
        return new EmptyBorder(10, 10, 10, 10);
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public Border getFooterBorder() {
        return new EmptyBorder(5, 5, 5, 5);
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public Border getCenterrBorder() {
        return new EmptyBorder(0, 5, 0, 5);
    }

    /**
     * DOCUMENT ME!
     */
    @Override
    public void dispose() {
        panMain.dispose();
        panArbeitsstand.dispose();
        panMassnahmen.dispose();
        panBemerkungen.dispose();
//        bindingGroup.unbind();
    }

    /**
     * DOCUMENT ME!
     *
     * @param  event  DOCUMENT ME!
     */
    @Override
    public void editorClosed(final EditorClosedEvent event) {
        panMain.editorClosed(event);
        panArbeitsstand.editorClosed(event);
        panMassnahmen.editorClosed(event);
        panBemerkungen.editorClosed(event);
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public boolean prepareForSave() {
        return true;
    }

    /**
     * DOCUMENT ME!
     *
     * @param   args  DOCUMENT ME!
     *
     * @throws  Exception  DOCUMENT ME!
     */
    public static void main(final String[] args) throws Exception {
        Log4JQuickConfig.configure4LumbermillOnLocalhost();
        final MappingComponent mc = new MappingComponent();
        CismapBroker.getInstance().setMappingComponent(mc);
        DevelopmentTools.createEditorFromRestfulConnection(
            DevelopmentTools.RESTFUL_CALLSERVER_CALLSERVER,
            "WUNDA_BLAU",
            null,
            true,
            "ALBO_FLAECHE",
            16521,
            1200,
            800);
    }

    @Override
    public String getTitle() {
        return null;
    }

    @Override
    public void setTitle(final String title) {
    }
}
