/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.cids.custom.objecteditors.wunda_blau;

import org.apache.log4j.Logger;

import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

import org.openide.awt.Mnemonics;
import org.openide.util.NbBundle;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;

import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

import de.cismet.cids.custom.objecteditors.utils.RendererTools;
import de.cismet.cids.custom.wunda_blau.band.SideComboBox;

import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.dynamics.CidsBeanStore;
import de.cismet.cids.dynamics.Disposable;

import de.cismet.connectioncontext.ConnectionContext;
import de.cismet.connectioncontext.ConnectionContextProvider;

import de.cismet.tools.gui.RoundedPanel;
import de.cismet.tools.gui.SemiRoundedPanel;

/**
 * DOCUMENT ME!
 *
 * @author   jruiz
 * @version  $Revision$, $Date$
 */
public class TreppeHandlaufPanel extends javax.swing.JPanel implements CidsBeanStore,
    Disposable,
    ConnectionContextProvider {

    //~ Static fields/initializers ---------------------------------------------

    private static final Logger LOG = Logger.getLogger(TreppeHandlaufPanel.class);

    //~ Instance fields --------------------------------------------------------

    private CidsBean cidsBean;
    private boolean editable = true;
    private ConnectionContext connectionContext;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    SideComboBox cbSide;
    JTextArea jTextArea8;
    JTextArea jTextArea9;
    JTextField jTextField22;
    TreppeBauteilZustandKostenPanel treppeBauteilZustandKostenPanel4;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new TreppeHandlaufPanel object.
     */
    public TreppeHandlaufPanel() {
        this(true, ConnectionContext.createDummy());
    }

    /**
     * Creates new form TreppeHandlaufPanel.
     *
     * @param  editable           DOCUMENT ME!
     * @param  connectionContext  DOCUMENT ME!
     */
    public TreppeHandlaufPanel(final boolean editable, final ConnectionContext connectionContext) {
        this.editable = editable;
        this.connectionContext = connectionContext;
        initComponents();
        jTextArea8.addKeyListener(new RendererTools.NoTabTextAreaKeyAdapter());
        jTextArea9.addKeyListener(new RendererTools.NoTabTextAreaKeyAdapter());
        setEditable(editable);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;
        bindingGroup = new BindingGroup();

        final JPanel jPanel26 = new JPanel();
        final RoundedPanel panAllgemein5 = new RoundedPanel();
        final SemiRoundedPanel panBeschreibungTitle5 = new SemiRoundedPanel();
        final JLabel lblHeaderAllgemein6 = new JLabel();
        final JPanel panBeschreibungContent5 = new JPanel();
        final JPanel jPanel36 = new JPanel();
        final JLabel jLabel62 = new JLabel();
        jTextField22 = new JTextField();
        final JLabel lblSide = new JLabel();
        cbSide = new SideComboBox();
        final JLabel jLabel69 = new JLabel();
        final Box.Filler filler4 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(0, 32767));
        final JScrollPane jScrollPane10 = new JScrollPane();
        jTextArea9 = new JTextArea();
        final JLabel jLabel67 = new JLabel();
        final Box.Filler filler5 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(0, 32767));
        final JScrollPane jScrollPane9 = new JScrollPane();
        jTextArea8 = new JTextArea();
        final Box.Filler filler1 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(0, 32767));
        final JPanel jPanel1 = new JPanel();
        treppeBauteilZustandKostenPanel4 = new TreppeBauteilZustandKostenPanel(editable);
        final Box.Filler filler3 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(0, 32767));
        final Box.Filler filler2 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(0, 32767));

        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new GridBagLayout());

        jPanel26.setName("jPanel26"); // NOI18N
        jPanel26.setOpaque(false);
        jPanel26.setLayout(new GridBagLayout());

        panAllgemein5.setName("panAllgemein5"); // NOI18N
        panAllgemein5.setLayout(new GridBagLayout());

        panBeschreibungTitle5.setBackground(new Color(51, 51, 51));
        panBeschreibungTitle5.setName("panBeschreibungTitle5"); // NOI18N
        panBeschreibungTitle5.setLayout(new FlowLayout());

        lblHeaderAllgemein6.setForeground(new Color(255, 255, 255));
        lblHeaderAllgemein6.setHorizontalAlignment(SwingConstants.CENTER);
        Mnemonics.setLocalizedText(
            lblHeaderAllgemein6,
            NbBundle.getMessage(TreppeHandlaufPanel.class, "TreppeHandlaufPanel.lblHeaderAllgemein6.text")); // NOI18N
        lblHeaderAllgemein6.setName("lblHeaderAllgemein6");                                                  // NOI18N
        panBeschreibungTitle5.add(lblHeaderAllgemein6);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        panAllgemein5.add(panBeschreibungTitle5, gridBagConstraints);

        panBeschreibungContent5.setName("panBeschreibungContent5"); // NOI18N
        panBeschreibungContent5.setOpaque(false);
        panBeschreibungContent5.setLayout(new GridBagLayout());

        jPanel36.setName("jPanel36"); // NOI18N
        jPanel36.setOpaque(false);
        jPanel36.setLayout(new GridBagLayout());

        Mnemonics.setLocalizedText(
            jLabel62,
            NbBundle.getMessage(TreppeHandlaufPanel.class, "TreppeHandlaufPanel.jLabel62.text")); // NOI18N
        jLabel62.setName("jLabel62");                                                             // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new Insets(1, 0, 1, 5);
        jPanel36.add(jLabel62, gridBagConstraints);

        jTextField22.setName("jTextField22"); // NOI18N

        Binding binding = Bindings.createAutoBinding(
                AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                ELProperty.create("${cidsBean.nummer}"),
                jTextField22,
                BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(1, 0, 1, 0);
        jPanel36.add(jTextField22, gridBagConstraints);

        Mnemonics.setLocalizedText(
            lblSide,
            NbBundle.getMessage(TreppeHandlaufPanel.class, "TreppeHandlaufPanel.lblSide.text", new Object[] {})); // NOI18N
        lblSide.setName("lblSide");                                                                               // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new Insets(1, 0, 1, 5);
        jPanel36.add(lblSide, gridBagConstraints);

        cbSide.setName("cbSide"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(1, 0, 1, 0);
        jPanel36.add(cbSide, gridBagConstraints);

        Mnemonics.setLocalizedText(
            jLabel69,
            NbBundle.getMessage(TreppeHandlaufPanel.class, "TreppeHandlaufPanel.jLabel69.text")); // NOI18N
        jLabel69.setVerticalAlignment(SwingConstants.TOP);
        jLabel69.setName("jLabel69");                                                             // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new Insets(1, 0, 1, 5);
        jPanel36.add(jLabel69, gridBagConstraints);

        filler4.setName("filler4"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(19, 0, 19, 0);
        jPanel36.add(filler4, gridBagConstraints);

        jScrollPane10.setName("jScrollPane10"); // NOI18N

        jTextArea9.setColumns(20);
        jTextArea9.setLineWrap(true);
        jTextArea9.setWrapStyleWord(true);
        jTextArea9.setName("jTextArea9"); // NOI18N

        binding = Bindings.createAutoBinding(
                AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                ELProperty.create("${cidsBean.beschreibung}"),
                jTextArea9,
                BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane10.setViewportView(jTextArea9);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(1, 0, 1, 0);
        jPanel36.add(jScrollPane10, gridBagConstraints);

        Mnemonics.setLocalizedText(
            jLabel67,
            NbBundle.getMessage(TreppeHandlaufPanel.class, "TreppeHandlaufPanel.jLabel67.text")); // NOI18N
        jLabel67.setVerticalAlignment(SwingConstants.TOP);
        jLabel67.setName("jLabel67");                                                             // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new Insets(1, 0, 1, 5);
        jPanel36.add(jLabel67, gridBagConstraints);

        filler5.setName("filler5"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(19, 0, 19, 0);
        jPanel36.add(filler5, gridBagConstraints);

        jScrollPane9.setName("jScrollPane9"); // NOI18N

        jTextArea8.setColumns(20);
        jTextArea8.setLineWrap(true);
        jTextArea8.setWrapStyleWord(true);
        jTextArea8.setName("jTextArea8"); // NOI18N

        binding = Bindings.createAutoBinding(
                AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                ELProperty.create("${cidsBean.bemerkung}"),
                jTextArea8,
                BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane9.setViewportView(jTextArea8);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(1, 0, 1, 0);
        jPanel36.add(jScrollPane9, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        panBeschreibungContent5.add(jPanel36, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panAllgemein5.add(panBeschreibungContent5, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.anchor = GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        jPanel26.add(panAllgemein5, gridBagConstraints);

        filler1.setName("filler1"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel26.add(filler1, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(0, 0, 0, 5);
        add(jPanel26, gridBagConstraints);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new GridBagLayout());

        treppeBauteilZustandKostenPanel4.setName("treppeBauteilZustandKostenPanel4"); // NOI18N

        binding = Bindings.createAutoBinding(
                AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                ELProperty.create("${cidsBean.zustand}"),
                treppeBauteilZustandKostenPanel4,
                BeanProperty.create("cidsBean"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(treppeBauteilZustandKostenPanel4, gridBagConstraints);

        filler3.setName("filler3"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(filler3, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.insets = new Insets(0, 5, 0, 0);
        add(jPanel1, gridBagConstraints);

        filler2.setName("filler2"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        add(filler2, gridBagConstraints);

        bindingGroup.bind();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  editable  DOCUMENT ME!
     */
    public void setEditable(final boolean editable) {
        this.editable = editable;

        if (editable) {
            RendererTools.makeWritable(jTextField22);
            RendererTools.makeWritable(jTextArea8);
            RendererTools.makeWritable(jTextArea9);
            RendererTools.makeWritable(cbSide);
        } else {
            RendererTools.makeReadOnly(jTextField22);
            RendererTools.makeReadOnly(jTextArea8);
            RendererTools.makeReadOnly(jTextArea9);
            RendererTools.makeReadOnly(cbSide);
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */

    @Override
    public ConnectionContext getConnectionContext() {
        return connectionContext;
    }

    @Override
    public CidsBean getCidsBean() {
        return cidsBean;
    }

    @Override
    public void setCidsBean(final CidsBean cidsBean) {
        bindingGroup.unbind();
        this.cidsBean = cidsBean;
        bindingGroup.bind();
        cbSide.setCidsBean(cidsBean);
    }

    @Override
    public void dispose() {
        bindingGroup.unbind();
        treppeBauteilZustandKostenPanel4.dispose();
        cbSide.setCidsBean(null);
        cidsBean = null;
    }
}
