/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.cids.custom.objectrenderer.utils.billing;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;

import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;

import de.cismet.cids.custom.objecteditors.utils.RendererTools;

import de.cismet.tools.gui.StaticSwingTools;

/**
 * DOCUMENT ME!
 *
 * @author   Gilles Baatz
 * @version  $Revision$, $Date$
 */
public class EMailTemplateChooserDialog extends javax.swing.JDialog {

    //~ Static fields/initializers ---------------------------------------------

    private static final transient org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(
            EMailTemplateChooserDialog.class);
    private static TemplateInfo templateInfo;
    private static ArrayList<Template> templates = new ArrayList<Template>();

    static {
        try {
            templateInfo =
                new ObjectMapper().readValue(TemplateInfo.class.getResourceAsStream(
                        "/de/cismet/cids/custom/billing/email_templates.json"),
                    TemplateInfo.class);

            templates = templateInfo.getTemplates();
        } catch (IOException ex) {
            LOG.error("Error when trying to read the email_templates.json", ex);
        }
    }

    //~ Instance fields --------------------------------------------------------

    private Template templateToReturn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdoptTemplate;
    private javax.swing.JComboBox cobTemplates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextArea txtaBody;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form EMailTemplateChooserDialog.
     */
    public EMailTemplateChooserDialog() {
        super();
        setModal(true);
        initComponents();
        RendererTools.makeReadOnly(jScrollPane1);
        RendererTools.makeReadOnly(txtSubject);
        RendererTools.makeReadOnly(txtaBody);

        final DefaultComboBoxModel<Template> model = new DefaultComboBoxModel<Template>(templates.toArray(
                    new Template[templates.size()]));
        cobTemplates.setModel(model);
        cobTemplates.setSelectedIndex(0);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * Shows the dialog and when the dialog is closed then it returns the chosen template.
     *
     * @return  DOCUMENT ME!
     */
    public Template showDialogAndReturnBody() {
        StaticSwingTools.showDialog(this);
        return templateToReturn;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtSubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaBody = new javax.swing.JTextArea();
        cobTemplates = new javax.swing.JComboBox();
        btnAdoptTemplate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        txtSubject.setText(org.openide.util.NbBundle.getMessage(
                EMailTemplateChooserDialog.class,
                "EMailTemplateChooserDialog.txtSubject.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        getContentPane().add(txtSubject, gridBagConstraints);

        txtaBody.setColumns(20);
        txtaBody.setRows(5);
        jScrollPane1.setViewportView(txtaBody);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        cobTemplates.setModel(new javax.swing.DefaultComboBoxModel(
                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cobTemplates.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    cobTemplatesActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        getContentPane().add(cobTemplates, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            btnAdoptTemplate,
            org.openide.util.NbBundle.getMessage(
                EMailTemplateChooserDialog.class,
                "EMailTemplateChooserDialog.btnAdoptTemplate.text")); // NOI18N
        btnAdoptTemplate.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnAdoptTemplateActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 5);
        getContentPane().add(btnAdoptTemplate, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel1,
            org.openide.util.NbBundle.getMessage(
                EMailTemplateChooserDialog.class,
                "EMailTemplateChooserDialog.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnAdoptTemplateActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnAdoptTemplateActionPerformed
        templateToReturn = (Template)cobTemplates.getSelectedItem();
        setVisible(false);
    }                                                                                    //GEN-LAST:event_btnAdoptTemplateActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void cobTemplatesActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cobTemplatesActionPerformed
        final Template template = (Template)cobTemplates.getSelectedItem();
        txtSubject.setText(template.getSubject());
        txtaBody.setText(template.getBody());
    }                                                                                //GEN-LAST:event_cobTemplatesActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  args  the command line arguments
     */
    public static void main(final String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EMailTemplateChooserDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EMailTemplateChooserDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EMailTemplateChooserDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EMailTemplateChooserDialog.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    final EMailTemplateChooserDialog dialog = new EMailTemplateChooserDialog();
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                            @Override
                            public void windowClosing(final java.awt.event.WindowEvent e) {
                                System.exit(0);
                            }
                        });
                    dialog.setVisible(true);
                }
            });
    }
}
