/*
 * TestRenderer.java
 *
 * Created on 23. August 2007, 12:19
 */

package de.cismet.cids.featurerenderer;

import de.cismet.cids.annotations.CidsAttribute;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JComponent;
import quicktime.QTException;
import quicktime.QTSession;
import quicktime.app.view.MoviePlayer;
import quicktime.app.view.QTFactory;
import quicktime.app.view.QTJComponent;
import quicktime.std.StdQTConstants;
import quicktime.std.StdQTException;
import quicktime.std.movies.Movie;
import quicktime.std.movies.MovieController;
import quicktime.std.movies.media.DataRef;

/**
 * de.cismet.cids.featurerenderer.BauvisfeatureRenderer
 * @author  hell
 */
public class BauvisfeatureRenderer extends  CustomCidsFeatureRenderer {
    @CidsAttribute("Objekt")
    String objectName;
    
    /** Creates new form TestRenderer */
    public BauvisfeatureRenderer() {
        initComponents();
        setPreferredSize(new Dimension(250,180));
//        setPreferredSize(new Dimension(450,150));
        //setMaximumSize(new Dimension(450,150));
        //setSize(new Dimension(250,190));
        
    }
    
    public void assign() {
        try {
            setOpaque(false);
            QTSession.open();
            // get movie from file
            DataRef urlRef = new DataRef(objectName);
           final  Movie movie = Movie.fromDataRef(urlRef,
                    StdQTConstants.newMovieActive);
            MoviePlayer player = new MoviePlayer(movie);
            MovieController cont=new MovieController(movie);
            QTJComponent qtjc = QTFactory.makeQTJComponent(player);
            
            JComponent jc = qtjc.asJComponent();
            jPanel1.add(jc,BorderLayout.CENTER);
            jc.setSize(240,180);
            //jPanel1.revalidate();
//            jPanel1.add(ccc.asComponent(),BorderLayout.SOUTH);
            //movie.start();
            jc.addMouseListener(new MouseListener() {
                public void mouseClicked(MouseEvent e) {
                    try {
                        movie.start();
                    } catch (StdQTException ex) {
                        ex.printStackTrace();
                    }
                }
                public void mouseEntered(MouseEvent e) {
                }
                public void mouseExited(MouseEvent e) {
                }
                public void mousePressed(MouseEvent e) {
                }
                public void mouseReleased(MouseEvent e) {
                }
            });
            
        } catch (StdQTException ex) {
            ex.printStackTrace();
        } catch (QTException ex) {
            ex.printStackTrace();
        }
        
        
        
    }
    public float getTransparency() {
        return 0.9f;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();

        jPanel1.setOpaque(false);
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
