/*
 * TestRenderer.java
 *
 * Created on 23. August 2007, 12:19
 */

package de.cismet.cids.featurerenderer;

import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JComponent;
import quicktime.QTException;
import quicktime.QTSession;
import quicktime.app.view.MoviePlayer;
import quicktime.app.view.QTComponent;
import quicktime.app.view.QTFactory;
import quicktime.app.view.QTJComponent;
import quicktime.io.OpenMovieFile;
import quicktime.io.QTFile;
import quicktime.std.StdQTException;
import quicktime.std.movies.Movie;
import quicktime.std.movies.MovieController;

/**
 *
 * @author  hell
 */
public class TestRenderer extends  CustomCidsFeatureRenderer {
    
    /** Creates new form TestRenderer */
    public TestRenderer() {
        initComponents();
        try {
            setOpaque(false);
            QTSession.open();
            // get movie from file
//            File f = new File("c:\\flug.mpeg");
            File f = new File("c:\\Rathaus.mov");
            OpenMovieFile omFile = OpenMovieFile.asRead(new QTFile(f));
            Movie movie = Movie.fromFile(omFile);
            MoviePlayer player = new MoviePlayer(movie);
                        MovieController cont=new MovieController(movie);
            QTJComponent qtjc = QTFactory.makeQTJComponent(player);
           
            JComponent jc = qtjc.asJComponent();
            jPanel1.add(jc,BorderLayout.CENTER);
//            jPanel1.add(ccc.asComponent(),BorderLayout.SOUTH);
            movie.start();
            
        } catch (StdQTException ex) {
            ex.printStackTrace();
        } catch (QTException ex) {
            ex.printStackTrace();
        }
    }
    
    public void assign() {
    }
    public float getTransparency() {
        return 0.9f;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();

        jPanel1.setOpaque(false);
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
