/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Alkis_pointRenderer.java
 *
 * Created on 10.09.2009, 15:52:16
 */
package de.cismet.cids.custom.objectrenderer.wunda_blau;

import de.aedsicad.aaaweb.service.alkis.info.ALKISInfoServices;
import de.aedsicad.aaaweb.service.util.Buchungsblatt;
import de.cismet.cids.custom.objectrenderer.utils.ObjectRendererUIUtils;
import de.cismet.cids.custom.objectrenderer.utils.alkis.SOAPAccessProvider;
import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.tools.metaobjectrenderer.CidsBeanRenderer;
import de.cismet.tools.CismetThreadPool;
import de.cismet.tools.collections.TypeSafeCollections;
import de.cismet.tools.gui.FooterComponentProvider;
import de.cismet.tools.gui.StaticSwingTools;
import de.cismet.tools.gui.TitleComponentProvider;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import org.jdesktop.swingx.error.ErrorInfo;

/**
 *
 * @author srichter
 */
public class Alkis_buchungsblattRenderer_old extends javax.swing.JPanel implements CidsBeanRenderer, TitleComponentProvider, FooterComponentProvider {

    private static final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(Alkis_buchungsblattRenderer_old.class);
    private final List<JLabel> retrieveableLabels;
    private SOAPAccessProvider soapProvider;
//    private ALKISSearchServices searchService;
    private ALKISInfoServices infoService;
    private Buchungsblatt buchungsblatt;
    private CidsBean cidsBean;
    private String title;

    /** Creates new form Alkis_pointRenderer */
    public Alkis_buchungsblattRenderer_old() {
        retrieveableLabels = TypeSafeCollections.newArrayList();
        try {
            soapProvider = new SOAPAccessProvider();
//            searchService = soapProvider.getAlkisSearchService();
            infoService = soapProvider.getAlkisInfoService();
        } catch (Exception ex) {
            log.fatal(ex, ex);
        }
        initComponents();
        retrieveableLabels.add(lblTxtEigentuemerNachname);
//        retrieveableLabels.add(lblTxtFlurstueckcode);
//        retrieveableLabels.add(lblTxtAbmarkung);
//        retrieveableLabels.add(lblTxtModellart);
//        retrieveableLabels.add(lblTxtDienststelle);
//        retrieveableLabels.add(lblTxtLand);
//        retrieveableLabels.add(lblTxtDienststelle);
//        retrieveableLabels.add(lblTxtAnlass);
//        retrieveableLabels.add(lblTxtBemerkungAbmarkung);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        panTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panFooter = new javax.swing.JPanel();
        hlGrundstuecksnachweisPdf = new org.jdesktop.swingx.JXHyperlink();
        hlGrundstuecksnachweisHtml = new org.jdesktop.swingx.JXHyperlink();
        hlBestandsnachweisPdf = new org.jdesktop.swingx.JXHyperlink();
        hlBestandsnachweisHtml = new org.jdesktop.swingx.JXHyperlink();
        lblTxtBuchungsblattcode = new javax.swing.JLabel();
        btnRetrieve = new javax.swing.JButton();
        lblBuchungsblattcode = new javax.swing.JLabel();
        lblTxtEigentuemerNachname = new javax.swing.JLabel();
        lblTxtFlurstueckcode = new javax.swing.JLabel();
        lblEigentuemernachname = new javax.swing.JLabel();
        lblFlurstueckcode = new javax.swing.JLabel();

        panTitle.setOpaque(false);
        panTitle.setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("TITLE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        panTitle.add(lblTitle, gridBagConstraints);

        panFooter.setOpaque(false);
        panFooter.setLayout(new java.awt.GridBagLayout());

        hlGrundstuecksnachweisPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/icons/pdf.png"))); // NOI18N
        hlGrundstuecksnachweisPdf.setText("Grundstücksnachweis PDF");
        hlGrundstuecksnachweisPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlGrundstuecksnachweisPdfActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panFooter.add(hlGrundstuecksnachweisPdf, gridBagConstraints);

        hlGrundstuecksnachweisHtml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/icons/text-html.png"))); // NOI18N
        hlGrundstuecksnachweisHtml.setText("Grundstücksnachweis HTML");
        hlGrundstuecksnachweisHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlGrundstuecksnachweisHtmlActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panFooter.add(hlGrundstuecksnachweisHtml, gridBagConstraints);

        hlBestandsnachweisPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/icons/pdf.png"))); // NOI18N
        hlBestandsnachweisPdf.setText("Bestandsnachweis PDF");
        hlBestandsnachweisPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlBestandsnachweisPdfActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panFooter.add(hlBestandsnachweisPdf, gridBagConstraints);

        hlBestandsnachweisHtml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/icons/text-html.png"))); // NOI18N
        hlBestandsnachweisHtml.setText("Bestandsnachweis HTML");
        hlBestandsnachweisHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlBestandsnachweisHtmlActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panFooter.add(hlBestandsnachweisHtml, gridBagConstraints);

        setLayout(new java.awt.GridBagLayout());

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.buchungsblattcode}"), lblTxtBuchungsblattcode, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("-");
        binding.setSourceUnreadableValue("<Error>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblTxtBuchungsblattcode, gridBagConstraints);

        btnRetrieve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/icons/network-wired.png"))); // NOI18N
        btnRetrieve.setText("Retrieve");
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnRetrieve, gridBagConstraints);

        lblBuchungsblattcode.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblBuchungsblattcode.setText("Buchungsblattcode:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblBuchungsblattcode, gridBagConstraints);

        lblTxtEigentuemerNachname.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblTxtEigentuemerNachname, gridBagConstraints);

        lblTxtFlurstueckcode.setText("...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblTxtFlurstueckcode, gridBagConstraints);

        lblEigentuemernachname.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblEigentuemernachname.setText("Eigentümer Nachname:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblEigentuemernachname, gridBagConstraints);

        lblFlurstueckcode.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblFlurstueckcode.setText("Flurstückcodes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblFlurstueckcode, gridBagConstraints);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private final String escapeHtmlSpaces(String toEscape) {
        if (toEscape != null) {
            toEscape = toEscape.replace(" ", "%20");
        }
        return toEscape;
    }

    public static final String fixBuchungslattCode(String buchungsblattCode) {
        if (buchungsblattCode != null) {
            final StringBuffer buchungsblattCodeSB = new StringBuffer(buchungsblattCode);
            //Fix SICAD-API-strangeness...
            while (buchungsblattCodeSB.length() < 14) {
                buchungsblattCodeSB.append(" ");
            }
            return buchungsblattCodeSB.toString();
        } else {
            return "";
        }
    }

    private final String getCompleteBuchungsblattCode() {
        if (cidsBean != null) {
            final Object buchungsblattCodeObj = cidsBean.getProperty("buchungsblattcode");
            if (buchungsblattCodeObj != null) {
                return fixBuchungslattCode(buchungsblattCodeObj.toString());
            }
        }
        return "";
    }

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
        final String buchungsblattCode = getCompleteBuchungsblattCode();
        if (buchungsblattCode.length() > 0) {
            CismetThreadPool.execute(new RetrieveWorker(buchungsblattCode));
        }
    }//GEN-LAST:event_btnRetrieveActionPerformed

//    private String getFirstFlurstueck() {
//        Object o = cidsBean.getProperty("landparcels");
//        if (o instanceof Collection) {
//            Collection stellen = (Collection) o;
//            if (stellen != null && stellen.size() > 0) {
//                return stellen.iterator().next().toString();
//            }
//        }
//        return "";
//    }
    private void hlGrundstuecksnachweisPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlGrundstuecksnachweisPdfActionPerformed
        try {
            String buchungsblattCode = getCompleteBuchungsblattCode();
            if (buchungsblattCode.length() > 0) {
                buchungsblattCode = escapeHtmlSpaces(buchungsblattCode);
                String url = "http://s102x083:8080/ASWeb34/ASA_AAAWeb/ALKISBuchNachweis?user=3atest&password=3atest&service=wuppertal&product=LB.A.G.G.NRW&id=" + buchungsblattCode + "&contentType=PDF&certificationType=9601";
                ObjectRendererUIUtils.openURL(url);
            }
        } catch (Exception ex) {
            log.error(ex);
        }
    }//GEN-LAST:event_hlGrundstuecksnachweisPdfActionPerformed

    private void hlGrundstuecksnachweisHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlGrundstuecksnachweisHtmlActionPerformed
        try {
            String buchungsblattCode = getCompleteBuchungsblattCode();
            if (buchungsblattCode.length() > 0) {
                buchungsblattCode = escapeHtmlSpaces(buchungsblattCode);
                String url = "http://s102x083:8080/ASWeb34/ASA_AAAWeb/ALKISBuchNachweis?user=3atest&password=3atest&service=wuppertal&product=LB.A.G.G.NRW&id=" + buchungsblattCode + "&contentType=HTML&certificationType=9601";
                ObjectRendererUIUtils.openURL(url);
            }
        } catch (Exception ex) {
            log.error(ex);
        }
    }//GEN-LAST:event_hlGrundstuecksnachweisHtmlActionPerformed

    private void hlBestandsnachweisPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlBestandsnachweisPdfActionPerformed
        try {
            String buchungsblattCode = getCompleteBuchungsblattCode();
            if (buchungsblattCode.length() > 0) {
                buchungsblattCode = escapeHtmlSpaces(buchungsblattCode);
                String url = "http://s102x083:8080/ASWeb34/ASA_AAAWeb/ALKISBuchNachweis?user=3atest&password=3atest&service=wuppertal&product=LB.A.B.G.NRW&id=" + buchungsblattCode + "&contentType=PDF&certificationType=9701";
                ObjectRendererUIUtils.openURL(url);
            }
        } catch (Exception ex) {
            log.error(ex);
        }
    }//GEN-LAST:event_hlBestandsnachweisPdfActionPerformed

    private void hlBestandsnachweisHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlBestandsnachweisHtmlActionPerformed
        try {
            String buchungsblattCode = getCompleteBuchungsblattCode();
            if (buchungsblattCode.length() > 0) {
                buchungsblattCode = escapeHtmlSpaces(buchungsblattCode);
                String url = "http://s102x083:8080/ASWeb34/ASA_AAAWeb/ALKISBuchNachweis?user=3atest&password=3atest&service=wuppertal&product=LB.A.B.G.NRW&id=" + buchungsblattCode + "&contentType=HTML&certificationType=9701";
                ObjectRendererUIUtils.openURL(url);
            }
        } catch (Exception ex) {
            log.error(ex);
        }
    }//GEN-LAST:event_hlBestandsnachweisHtmlActionPerformed

    @Override
    public CidsBean getCidsBean() {
        return cidsBean;
    }

    @Override
    public void setCidsBean(CidsBean cb) {
        if (cb != null) {
            this.cidsBean = cb;
            lblTxtFlurstueckcode.setText(String.valueOf(cidsBean.getProperty("landparcels")));
            bindingGroup.unbind();
            bindingGroup.bind();
        }
    }

    @Override
    public String getTitle() {
        return title;
    }

    @Override
    public void setTitle(String title) {
        if (title == null) {
            title = "<Error>";
        } else {
            title = "Buchungsblatt " + title;
        }
        this.title = title;
        lblTitle.setText(this.title);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetrieve;
    private org.jdesktop.swingx.JXHyperlink hlBestandsnachweisHtml;
    private org.jdesktop.swingx.JXHyperlink hlBestandsnachweisPdf;
    private org.jdesktop.swingx.JXHyperlink hlGrundstuecksnachweisHtml;
    private org.jdesktop.swingx.JXHyperlink hlGrundstuecksnachweisPdf;
    private javax.swing.JLabel lblBuchungsblattcode;
    private javax.swing.JLabel lblEigentuemernachname;
    private javax.swing.JLabel lblFlurstueckcode;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTxtBuchungsblattcode;
    private javax.swing.JLabel lblTxtEigentuemerNachname;
    private javax.swing.JLabel lblTxtFlurstueckcode;
    private javax.swing.JPanel panFooter;
    private javax.swing.JPanel panTitle;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public JComponent getTitleComponent() {
        return panTitle;
    }

    @Override
    public JComponent getFooterComponent() {
        return panFooter;
    }

    final class RetrieveWorker extends SwingWorker<Buchungsblatt, Void> {

        public RetrieveWorker(String buchungsblattCode) {
            this.buchungsBlattCode = buchungsblattCode;
            timer = new Timer(250, new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    if (waitStat.length() < 11) {
                        waitStat += ".";
                    } else {
                        waitStat = ".";
                    }
                    for (final JLabel label : retrieveableLabels) {
                        label.setText(waitStat);
                    }
                }
            });
            btnRetrieve.setVisible(false);
            timer.start();
        }
        private final String buchungsBlattCode;
        private String waitStat = "";
        private final Timer timer;

        @Override
        protected Buchungsblatt doInBackground() throws Exception {

            return infoService.getBuchungsblatt(soapProvider.getIdentityCard(), soapProvider.getService(), buchungsBlattCode);
        }

        private final void restoreOnException() {
            btnRetrieve.setVisible(true);
            for (JLabel label : retrieveableLabels) {
                label.setText("...");
            }
        }

        @Override
        protected void done() {
            timer.stop();
            try {
                final Buchungsblatt buchungsblatt = get();
                if (buchungsblatt != null) {
                    Alkis_buchungsblattRenderer_old.this.buchungsblatt = buchungsblatt;
//                    Alkis_buchungsblattRenderer.this.bindingGroup.unbind();
//                    Alkis_buchungsblattRenderer.this.bindingGroup.bind();

                    //TODO this is quick and dirty for tesing only!
                    lblTxtEigentuemerNachname.setText(buchungsblatt.getOwners()[0].getSurName());

//                    lblTxtModellart.setText(point.getModellArt());
//                    lblTxtDienststelle.setText(point.getZustaendigeStelleStelle());
//                    lblTxtLand.setText(point.getZustaendigeStelleLand());
//                    lblTxtBeginn.setText(point.getLebenszeitIntervallBeginnt());
//                    lblTxtEnde.setText(point.getLebenszeitIntervallEndet());
//                    lblTxtAnlass.setText(point.getAnlass());
//                    lblTxtBemerkungAbmarkung.setText(point.getBemerkungZurAbmarkungName());
                }
            } catch (InterruptedException ex) {
                restoreOnException();
                log.warn(ex, ex);
            } catch (Exception ex) {
                //TODO show error message to user?
                restoreOnException();
                org.jdesktop.swingx.error.ErrorInfo ei = new ErrorInfo("Fehler beim Retrieve", ex.getMessage(), null, null, ex, Level.ALL, null);
                org.jdesktop.swingx.JXErrorPane.showDialog(StaticSwingTools.getParentFrame(Alkis_buchungsblattRenderer_old.this), ei);
                log.error(ex, ex);
            }
        }
    }
}
