/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Alkis_pointRenderer.java
 *
 * Created on 10.09.2009, 15:52:16
 */
package de.cismet.cids.custom.objectrenderer.wunda_blau;

import de.aedsicad.aaaweb.service.util.Buchungsblatt;
import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.tools.metaobjectrenderer.CidsBeanRenderer;
import de.cismet.tools.gui.BorderProvider;
import de.cismet.tools.gui.FooterComponentProvider;
import de.cismet.tools.gui.RoundedPanel;
import de.cismet.tools.gui.TitleComponentProvider;
import javax.swing.JComponent;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author srichter
 */
public class Alkis_adresseRenderer extends javax.swing.JPanel implements CidsBeanRenderer, BorderProvider, TitleComponentProvider, FooterComponentProvider {

    private static final org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(Alkis_adresseRenderer.class);
//    private SOAPAccessProvider soapProvider;
//    private ALKISInfoServices infoService;
    private Buchungsblatt buchungsblatt;
    private CidsBean cidsBean;
    private String title;

    /** Creates new form Alkis_pointRenderer */
    public Alkis_adresseRenderer() {
//        try {
//            soapProvider = new SOAPAccessProvider();
//            infoService = soapProvider.getAlkisInfoService();
//        } catch (Exception ex) {
//            log.fatal(ex, ex);
//        }
        initComponents();
        blWait.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        panTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        blWait = new org.jdesktop.swingx.JXBusyLabel();
        panFooter = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        panAdresse = new RoundedPanel();
        srpHeadAdresse = new de.cismet.tools.gui.SemiRoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        panAdresseContent = new RoundedPanel();
        lblDescStrasse = new javax.swing.JLabel();
        lblDescHausnummer = new javax.swing.JLabel();
        lblStrasse = new javax.swing.JLabel();
        lblHausnummer = new javax.swing.JLabel();
        panGebaeude = new RoundedPanel();
        srpHeadGebaeude = new de.cismet.tools.gui.SemiRoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        panGebaeudeContent = new javax.swing.JPanel();
        lblDescFunktion = new javax.swing.JLabel();
        lblDescStockwerke = new javax.swing.JLabel();
        lblFunktion = new javax.swing.JLabel();
        lblStockwerke = new javax.swing.JLabel();
        lblDescBauweise = new javax.swing.JLabel();
        lblBauweise = new javax.swing.JLabel();

        panTitle.setOpaque(false);
        panTitle.setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("TITLE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        panTitle.add(lblTitle, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 5);
        panTitle.add(blWait, gridBagConstraints);

        panFooter.setOpaque(false);
        panFooter.setLayout(new java.awt.GridBagLayout());

        jPanel9.setMaximumSize(new java.awt.Dimension(40, 40));
        jPanel9.setMinimumSize(new java.awt.Dimension(40, 40));
        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(40, 40));
        panFooter.add(jPanel9, new java.awt.GridBagConstraints());

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        panAdresse.setOpaque(false);
        panAdresse.setLayout(new java.awt.BorderLayout());

        srpHeadAdresse.setBackground(java.awt.Color.darkGray);
        srpHeadAdresse.setLayout(new java.awt.GridBagLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adresse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        srpHeadAdresse.add(jLabel1, gridBagConstraints);

        panAdresse.add(srpHeadAdresse, java.awt.BorderLayout.NORTH);

        panAdresseContent.setOpaque(false);
        panAdresseContent.setLayout(new java.awt.GridBagLayout());

        lblDescStrasse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDescStrasse.setText("Straße:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        panAdresseContent.add(lblDescStrasse, gridBagConstraints);

        lblDescHausnummer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDescHausnummer.setText("Hausnummer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        panAdresseContent.add(lblDescHausnummer, gridBagConstraints);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.strasse}"), lblStrasse, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("keine Angabe");
        binding.setSourceUnreadableValue("<Error>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAdresseContent.add(lblStrasse, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.nummer}"), lblHausnummer, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("keine Angabe");
        binding.setSourceUnreadableValue("<Error>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAdresseContent.add(lblHausnummer, gridBagConstraints);

        panAdresse.add(panAdresseContent, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(panAdresse, gridBagConstraints);

        panGebaeude.setOpaque(false);
        panGebaeude.setLayout(new java.awt.BorderLayout());

        srpHeadGebaeude.setBackground(java.awt.Color.darkGray);
        srpHeadGebaeude.setLayout(new java.awt.GridBagLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gebäude");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        srpHeadGebaeude.add(jLabel2, gridBagConstraints);

        panGebaeude.add(srpHeadGebaeude, java.awt.BorderLayout.NORTH);

        panGebaeudeContent.setOpaque(false);
        panGebaeudeContent.setLayout(new java.awt.GridBagLayout());

        lblDescFunktion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDescFunktion.setText("Funktion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        panGebaeudeContent.add(lblDescFunktion, gridBagConstraints);

        lblDescStockwerke.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDescStockwerke.setText("Oberirdische Geschosse:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        panGebaeudeContent.add(lblDescStockwerke, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.gebaeude.funktion}"), lblFunktion, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("keine Angabe");
        binding.setSourceUnreadableValue("<Error>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panGebaeudeContent.add(lblFunktion, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.gebaeude.geschosse_oberirdisch}"), lblStockwerke, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("keine Angabe");
        binding.setSourceUnreadableValue("<Error>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panGebaeudeContent.add(lblStockwerke, gridBagConstraints);

        lblDescBauweise.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDescBauweise.setText("Bauweise:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        panGebaeudeContent.add(lblDescBauweise, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, org.jdesktop.beansbinding.ELProperty.create("${cidsBean.gebaeude.bauweise}"), lblBauweise, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("keine Angabe");
        binding.setSourceUnreadableValue("<Error>");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panGebaeudeContent.add(lblBauweise, gridBagConstraints);

        panGebaeude.add(panGebaeudeContent, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(panGebaeude, gridBagConstraints);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setCidsBean(CidsBean cb) {
        if (cb != null) {
            cidsBean = cb;
            final Object gebaeudeObj = cidsBean.getProperty("gebaeude");
            if (!(gebaeudeObj instanceof CidsBean)) {
                panGebaeude.setVisible(false);
            } else {
                panGebaeude.setVisible(true);
            }
            bindingGroup.unbind();
            bindingGroup.bind();
        }
    }

    @Override
    public String getTitle() {
        return title;
    }

    @Override
    public void setTitle(String title) {
        if (title == null) {
            title = "<Error>";
        } else {
            title = "Adresse " + title;
        }
        this.title = title;
        lblTitle.setText(this.title);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXBusyLabel blWait;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblBauweise;
    private javax.swing.JLabel lblDescBauweise;
    private javax.swing.JLabel lblDescFunktion;
    private javax.swing.JLabel lblDescHausnummer;
    private javax.swing.JLabel lblDescStockwerke;
    private javax.swing.JLabel lblDescStrasse;
    private javax.swing.JLabel lblFunktion;
    private javax.swing.JLabel lblHausnummer;
    private javax.swing.JLabel lblStockwerke;
    private javax.swing.JLabel lblStrasse;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panAdresse;
    private javax.swing.JPanel panAdresseContent;
    private javax.swing.JPanel panFooter;
    private javax.swing.JPanel panGebaeude;
    private javax.swing.JPanel panGebaeudeContent;
    private javax.swing.JPanel panTitle;
    private de.cismet.tools.gui.SemiRoundedPanel srpHeadAdresse;
    private de.cismet.tools.gui.SemiRoundedPanel srpHeadGebaeude;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public JComponent getTitleComponent() {
        return panTitle;
    }

    @Override
    public JComponent getFooterComponent() {
        return panFooter;
    }

    /**
     * @return the buchungsblatt
     */
    public Object getBuchungsblatt() {
        return buchungsblatt;
    }

    /**
     * @param buchungsblatt the buchungsblatt to set
     */
    public void setBuchungsblatt(Buchungsblatt buchungsblatt) {
        this.buchungsblatt = buchungsblatt;
    }

    private final void setWaiting(boolean waiting) {
        blWait.setVisible(waiting);
        blWait.setBusy(waiting);
    }

    private final boolean isWaiting() {
        return blWait.isBusy();
    }

    @Override
    public Border getTitleBorder() {
        return new EmptyBorder(10, 10, 10, 10);
    }

    @Override
    public Border getFooterBorder() {
        return new EmptyBorder(5, 5, 5, 5);
    }

    @Override
    public Border getCenterrBorder() {
        return new EmptyBorder(5, 5, 5, 5);
    }

    @Override
    public CidsBean getCidsBean() {
        return cidsBean;
    }
}
