/*
 * Copyright (C) 2011 cismet GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AlkisBuchungsblattAggregationRenderer.java
 *
 * Created on 18.07.2011, 16:28:22
 */
package de.cismet.cids.custom.objectrenderer.wunda_blau;

import com.vividsolutions.jts.geom.Geometry;
import de.cismet.cids.custom.objectrenderer.utils.ObjectRendererUtils;
import de.cismet.cids.custom.objectrenderer.utils.alkis.AlkisUtils;
import de.cismet.cids.custom.utils.alkis.AlkisConstants;
import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.tools.metaobjectrenderer.CidsBeanAggregationRenderer;
import de.cismet.cismap.commons.CrsTransformer;
import de.cismet.cismap.commons.XBoundingBox;
import de.cismet.cismap.commons.features.DefaultStyledFeature;
import de.cismet.cismap.commons.features.FeatureCollection;
import de.cismet.cismap.commons.features.StyledFeature;
import de.cismet.cismap.commons.gui.MappingComponent;
import de.cismet.cismap.commons.gui.layerwidget.ActiveLayerModel;
import de.cismet.cismap.commons.raster.wms.simple.SimpleWMS;
import de.cismet.cismap.commons.raster.wms.simple.SimpleWmsGetMapUrl;
import de.cismet.tools.gui.RoundedPanel;
import de.cismet.tools.gui.StaticSwingTools;
import de.cismet.tools.gui.downloadmanager.DownloadManager;
import de.cismet.tools.gui.downloadmanager.DownloadManagerDialog;
import de.cismet.tools.gui.downloadmanager.MultipleDownload;
import de.cismet.tools.gui.downloadmanager.SingleDownload;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;
import org.apache.log4j.Logger;
import org.openide.util.NbBundle;

/**
 *
 * @author jweintraut
 */
public class AlkisBuchungsblattAggregationRenderer extends javax.swing.JPanel implements CidsBeanAggregationRenderer {
    private static final Logger LOG = Logger.getLogger(AlkisBuchungsblattAggregationRenderer.class);

    private static final String PRODUCT_ACTION_TAG_BESTANDSNACHWEIS_NRW = "custom.alkis.product.bestandsnachweis_nrw";
    private static final String PRODUCT_ACTION_TAG_BESTANDSNACHWEIS_KOM = "custom.alkis.product.bestandsnachweis_kom";
    private static final String PRODUCT_ACTION_TAG_BESTANDSNACHWEIS_KOM_INTERN = "custom.alkis.product.bestandsnachweis_kom_intern";
    
    private static final Color COLOR_FEATURE_DEFAULT = new Color(1, 0, 0, 0.5f);
    private static final Color COLOR_FEATURE_HIGHLIGHTED = new Color(0, 1, 0, 0.5f);
    
    
    private Collection<CidsBean> cidsBeans;
    private BuchungsblattTableModel tableModel;
    private MappingComponent map;
    private CidsBean selectedCidsBean;
    private Map<CidsBean, Collection<StyledFeature>> features;
    private Thread mapThread;

    /** Creates new form AlkisBuchungsblattAggregationRenderer */
    public AlkisBuchungsblattAggregationRenderer() {
        tableModel = new BuchungsblattTableModel();
        initComponents();
        
        map = new MappingComponent();
        pnlMap.add(map, BorderLayout.CENTER);
        tblBuchungsblaetter.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                ListSelectionModel lsm = (ListSelectionModel)e.getSource();
                
                if(lsm.isSelectionEmpty()) {
                    selectedCidsBean = null;
                } else {
                    selectedCidsBean = tableModel.get(lsm.getLeadSelectionIndex());
                }
                changeMap();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlButtons = new RoundedPanel();
        srpHeaderButtons = new de.cismet.tools.gui.SemiRoundedPanel();
        lblHeaderButtons = new javax.swing.JLabel();
        jxlBestandsnachweisNRW = new org.jdesktop.swingx.JXHyperlink();
        jxlBestandsnachweisKommunal = new org.jdesktop.swingx.JXHyperlink();
        jxlBestandsnachweisKommunalIntern = new org.jdesktop.swingx.JXHyperlink();
        pnlBuchungsblaetter = new RoundedPanel();
        srpHeaderBuchungsblaetter = new de.cismet.tools.gui.SemiRoundedPanel();
        lblHeaderBuchungsblaetter = new javax.swing.JLabel();
        scpBuchungsblaetter = new javax.swing.JScrollPane();
        tblBuchungsblaetter = new javax.swing.JTable();
        pnlMap = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        pnlButtons.setOpaque(false);
        pnlButtons.setLayout(new java.awt.GridBagLayout());

        srpHeaderButtons.setBackground(java.awt.Color.darkGray);
        srpHeaderButtons.setLayout(new java.awt.GridBagLayout());

        lblHeaderButtons.setForeground(java.awt.Color.white);
        lblHeaderButtons.setText(org.openide.util.NbBundle.getMessage(AlkisBuchungsblattAggregationRenderer.class, "AlkisBuchungsblattAggregationRenderer.lblHeaderButtons.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        srpHeaderButtons.add(lblHeaderButtons, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        pnlButtons.add(srpHeaderButtons, gridBagConstraints);

        jxlBestandsnachweisNRW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/icons/pdf.png"))); // NOI18N
        jxlBestandsnachweisNRW.setText(org.openide.util.NbBundle.getMessage(AlkisBuchungsblattAggregationRenderer.class, "AlkisBuchungsblattAggregationRenderer.jxlBestandsnachweisNRW.text")); // NOI18N
        jxlBestandsnachweisNRW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxlBestandsnachweisNRWActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 7, 10);
        pnlButtons.add(jxlBestandsnachweisNRW, gridBagConstraints);

        jxlBestandsnachweisKommunal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/icons/pdf.png"))); // NOI18N
        jxlBestandsnachweisKommunal.setText(org.openide.util.NbBundle.getMessage(AlkisBuchungsblattAggregationRenderer.class, "AlkisBuchungsblattAggregationRenderer.jxlBestandsnachweisKommunal.text")); // NOI18N
        jxlBestandsnachweisKommunal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxlBestandsnachweisKommunalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 7, 10);
        pnlButtons.add(jxlBestandsnachweisKommunal, gridBagConstraints);

        jxlBestandsnachweisKommunalIntern.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/cids/custom/icons/pdf.png"))); // NOI18N
        jxlBestandsnachweisKommunalIntern.setText(org.openide.util.NbBundle.getMessage(AlkisBuchungsblattAggregationRenderer.class, "AlkisBuchungsblattAggregationRenderer.jxlBestandsnachweisKommunalIntern.text")); // NOI18N
        jxlBestandsnachweisKommunalIntern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxlBestandsnachweisKommunalInternActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 10, 7, 10);
        pnlButtons.add(jxlBestandsnachweisKommunalIntern, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        add(pnlButtons, gridBagConstraints);

        pnlBuchungsblaetter.setMinimumSize(new java.awt.Dimension(309, 67));
        pnlBuchungsblaetter.setOpaque(false);
        pnlBuchungsblaetter.setPreferredSize(new java.awt.Dimension(309, 446));
        pnlBuchungsblaetter.setLayout(new java.awt.GridBagLayout());

        srpHeaderBuchungsblaetter.setBackground(java.awt.Color.darkGray);
        srpHeaderBuchungsblaetter.setLayout(new java.awt.GridBagLayout());

        lblHeaderBuchungsblaetter.setForeground(java.awt.Color.white);
        lblHeaderBuchungsblaetter.setText(org.openide.util.NbBundle.getMessage(AlkisBuchungsblattAggregationRenderer.class, "AlkisBuchungsblattAggregationRenderer.lblHeaderBuchungsblaetter.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        srpHeaderBuchungsblaetter.add(lblHeaderBuchungsblaetter, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        pnlBuchungsblaetter.add(srpHeaderBuchungsblaetter, gridBagConstraints);

        scpBuchungsblaetter.setPreferredSize(new java.awt.Dimension(250, 402));

        tblBuchungsblaetter.setModel(tableModel);
        tblBuchungsblaetter.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblBuchungsblaetter.setShowVerticalLines(false);
        scpBuchungsblaetter.setViewportView(tblBuchungsblaetter);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.35;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlBuchungsblaetter.add(scpBuchungsblaetter, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        add(pnlBuchungsblaetter, gridBagConstraints);

        pnlMap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlMap.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(pnlMap, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jxlBestandsnachweisNRWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxlBestandsnachweisNRWActionPerformed
        downloadEinzelnachweisProduct(tableModel.getSelectedCidsBeans(), jxlBestandsnachweisNRW.getText(), AlkisUtils.PRODUCTS.BESTANDSNACHWEIS_NRW_PDF, PRODUCT_ACTION_TAG_BESTANDSNACHWEIS_NRW);
}//GEN-LAST:event_jxlBestandsnachweisNRWActionPerformed

    private void jxlBestandsnachweisKommunalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxlBestandsnachweisKommunalActionPerformed
        downloadEinzelnachweisProduct(tableModel.getSelectedCidsBeans(), jxlBestandsnachweisKommunal.getText(), AlkisUtils.PRODUCTS.BESTANDSNACHWEIS_KOMMUNAL_PDF, PRODUCT_ACTION_TAG_BESTANDSNACHWEIS_KOM);
}//GEN-LAST:event_jxlBestandsnachweisKommunalActionPerformed

    private void jxlBestandsnachweisKommunalInternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxlBestandsnachweisKommunalInternActionPerformed
        downloadEinzelnachweisProduct(tableModel.getSelectedCidsBeans(), jxlBestandsnachweisKommunalIntern.getText(), AlkisUtils.PRODUCTS.BESTANDSNACHWEIS_KOMMUNAL_INTERN_PDF, PRODUCT_ACTION_TAG_BESTANDSNACHWEIS_KOM_INTERN);
}//GEN-LAST:event_jxlBestandsnachweisKommunalInternActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXHyperlink jxlBestandsnachweisKommunal;
    private org.jdesktop.swingx.JXHyperlink jxlBestandsnachweisKommunalIntern;
    private org.jdesktop.swingx.JXHyperlink jxlBestandsnachweisNRW;
    private javax.swing.JLabel lblHeaderBuchungsblaetter;
    private javax.swing.JLabel lblHeaderButtons;
    private javax.swing.JPanel pnlBuchungsblaetter;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlMap;
    private javax.swing.JScrollPane scpBuchungsblaetter;
    private de.cismet.tools.gui.SemiRoundedPanel srpHeaderBuchungsblaetter;
    private de.cismet.tools.gui.SemiRoundedPanel srpHeaderButtons;
    private javax.swing.JTable tblBuchungsblaetter;
    // End of variables declaration//GEN-END:variables

    @Override
    public Collection<CidsBean> getCidsBeans() {
        return cidsBeans;
    }

    @Override
    public void setCidsBeans(Collection<CidsBean> beans) {
        if(beans != null) {
            cidsBeans = beans;
            tableModel.setCidsBeans(cidsBeans);
            initMap();
            
            if(tblBuchungsblaetter != null && tblBuchungsblaetter.getColumnModel() != null) {
                final TableColumn column = tblBuchungsblaetter.getColumnModel().getColumn(0);
                if(column != null) {
                    column.setPreferredWidth(20);
                }
            }
        }
    }

    @Override
    public void dispose() {
        map.dispose();
    }

    @Override
    public String getTitle() {
        return NbBundle.getMessage(AlkisBuchungsblattAggregationRenderer.class, "AlkisBuchungsblattAggregationRenderer.title", (cidsBeans != null ? cidsBeans.size() : "0"));
    }

    @Override
    public void setTitle(String title) {
        //NOP
    }
    
    private void initMap() {
        Map<CidsBean, Collection<Geometry>> geometriesBuchungsblaetter = new HashMap<CidsBean, Collection<Geometry>>(cidsBeans.size());

        for (final CidsBean buchungsblatt : cidsBeans) {
            final Collection<Geometry> geometriesBuchungsblatt = new LinkedList<Geometry>();

            for(CidsBean landparcel : buchungsblatt.getBeanCollectionProperty("landparcels")) {
                final Object geometry = landparcel.getProperty("geometrie.geo_field");
                if (geometry instanceof Geometry) {
                    final Geometry transformedGeometry = CrsTransformer.transformToGivenCrs((Geometry) geometry, AlkisConstants.COMMONS.SRS_SERVICE);
                    geometriesBuchungsblatt.add(transformedGeometry);
                }
            }

            geometriesBuchungsblaetter.put(buchungsblatt, geometriesBuchungsblatt);
        }

        mapThread = new Thread(new InitialiseMapRunnable(geometriesBuchungsblaetter));
        if (EventQueue.isDispatchThread()) {
            mapThread.start();
        } else {
            EventQueue.invokeLater(mapThread);
        }
        
        revalidate();
        repaint();
    }
    
    private void changeMap() {
        if(mapThread != null && mapThread.isAlive()) {
            if(features == null) {
                //Initialising the map is still running. Don't change the map now.
                return;
            } else {
                //Map is initialised. Can be changed.
                mapThread.interrupt();
            }
        }
        
        mapThread = new Thread(new ChangeMapRunnable(tableModel.getSelectedCidsBeans(), selectedCidsBean));
        if (EventQueue.isDispatchThread()) {
            mapThread.start();
        } else {
            EventQueue.invokeLater(mapThread);
        }
        
        revalidate();
        repaint();
    }
    
    private void changeButtonAvailability(final boolean enable) {
        jxlBestandsnachweisNRW.setEnabled(enable);
        jxlBestandsnachweisKommunal.setEnabled(enable);
        jxlBestandsnachweisKommunalIntern.setEnabled(enable);
    }
    
    private void downloadEinzelnachweisProduct(Collection<CidsBean> cidsBeans, String downloadTitle, String product, String actionTag) {
        if(!ObjectRendererUtils.checkActionTag(actionTag)) {
            showNoProductPermissionWarning();
            //return;
        }
        
        if(!DownloadManagerDialog.showAskingForUserTitle(StaticSwingTools.getParentFrame(this))) {
            return;
        }
        final String jobname = DownloadManagerDialog.getJobname();
        if(jobname == null || jobname.trim().length() <= 0) {
            return;
        }
        
        List<SingleDownload> downloads = new LinkedList<SingleDownload>();
        
        for(CidsBean buchungsblatt : cidsBeans) {
            String queryID = getCompleteBuchungsblattCode(buchungsblatt);
            URL url = null;
            
            if(queryID == null || queryID.trim().length() <= 0) {
                continue;
            }
            
            queryID = AlkisUtils.escapeHtmlSpaces(queryID);
            
            try {
                url = AlkisUtils.PRODUCTS.productEinzelNachweisUrl(queryID, product);
            } catch (MalformedURLException ex) {
                ObjectRendererUtils.showExceptionWindowToUser(
                        "Fehler beim Aufruf des Produkts: " + product,
                        ex,
                        AlkisBuchungsblattAggregationRenderer.this);
                LOG.error("The URL to download product '" + product + "' (actionTag: " + actionTag + ") could not be constructed.", ex);
            }
            
            if (url != null) {
                downloads.add(new SingleDownload(url, "", jobname, downloadTitle, product, ".pdf"));
            }
        }
    
        if(downloads.size() > 1) {
            DownloadManager.instance().add(new MultipleDownload(downloads, jobname));
        } else if(downloads.size() == 1) {
            DownloadManager.instance().add(downloads.get(0));
        }
    }
    
    private String fixBuchungslattCode(final String buchungsblattcode) {
        String result = "";
        
        if (buchungsblattcode != null) {
            final StringBuffer buchungsblattcodeBuffer = new StringBuffer(buchungsblattcode);
            
            // Fix SICAD-API-strangeness...
            while (buchungsblattcodeBuffer.length() < 14) {
                buchungsblattcodeBuffer.append(" ");
            }
            
            result = buchungsblattcodeBuffer.toString();
        }
        
        return result;
    }

    private String getCompleteBuchungsblattCode(CidsBean cidsBean) {
        String result = "";
        
        if (cidsBean != null) {
            final Object buchungsblattcode = cidsBean.getProperty("buchungsblattcode");
            
            if (buchungsblattcode != null) {
                result = fixBuchungslattCode(buchungsblattcode.toString());
            }
        }
        
        return result;
    }

    private void showNoProductPermissionWarning() {
        JOptionPane.showMessageDialog(this, "Sie besitzen keine Berechtigung zur Erzeugung dieses Produkts!");
    }
    
    private class BuchungsblattTableModel extends AbstractTableModel {
        private List<CidsBean> selectedCidsBeans;
        private List<CidsBean> cidsBeansToShow;
        
        @Override
        public int getRowCount() {
            if(cidsBeansToShow == null) {
                return 0;
            }
            
            return cidsBeansToShow.size();
        }

        @Override
        public int getColumnCount() {
            if(cidsBeansToShow == null) {
                return 0;
            }
            
            return 3;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if(columnIndex == 0) {
                return Boolean.class;
            } else {
                return String.class;
            }
        }

        @Override
        public String getColumnName(int column) {
            return NbBundle.getMessage(AlkisBuchungsblattAggregationRenderer.class, "AlkisBuchungsblattAggregationRenderer.BuchungsblattTableModel.getColumnName(" + column + ")");
        }
        
        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            if(cidsBeansToShow == null) {
                return null;
            }
            
            CidsBean buchungsblatt = cidsBeansToShow.get(rowIndex);
            if(columnIndex == 0) {
                return selectedCidsBeans.contains(buchungsblatt);
            } else if(columnIndex == 1) {
                return buchungsblatt.getProperty("blattart").toString();
            } else {
                return buchungsblatt.getProperty("buchungsblattcode").toString();
            }
        }
        
        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 0;
        }
        
        public void setCidsBeans(Collection<CidsBean> cidsBeans) {
            if(cidsBeans != null) {
                cidsBeansToShow = new LinkedList<CidsBean>(cidsBeans);
                Collections.sort(cidsBeansToShow, new BuchungsblattComparator());
                selectedCidsBeans = new LinkedList<CidsBean>(cidsBeansToShow);
                fireTableStructureChanged();
            }
        }
    
        public List<CidsBean> getSelectedCidsBeans() {
            return selectedCidsBeans;
        }

        @Override
        public void setValueAt(Object value, int row, int column) {
            if(column != 0) {
                return;
            }
            
            CidsBean cidsBean = cidsBeansToShow.get(row);
            if(selectedCidsBeans.contains(cidsBean)) {
                selectedCidsBeans.remove(cidsBean);
            } else {
                selectedCidsBeans.add(cidsBean);
                Collections.sort(selectedCidsBeans, new BuchungsblattComparator());
            }
            
            fireTableRowsUpdated(row, row);
            changeMap();
            changeButtonAvailability(selectedCidsBeans.size() > 0);
        }
        
        public CidsBean get(int index) {
            return cidsBeansToShow.get(index);
        }
    }
    
    private class BuchungsblattComparator implements Comparator<CidsBean> {
        @Override
        public int compare(CidsBean cidsBean1, CidsBean cidsBean2) {
            if(cidsBean1 == null && cidsBean2 == null) {
                return 0;
            } else if(cidsBean1 == null) {
                return -1;
            } else if(cidsBean2 == null) {
                return 1;
            }
            
            int typeComparison = cidsBean1.getProperty("blattart").toString().compareTo(cidsBean2.getProperty("blattart").toString());
            
            if(typeComparison != 0) {
                return typeComparison;
            } else {
                return cidsBean1.getProperty("buchungsblattcode").toString().compareTo(cidsBean2.getProperty("buchungsblattcode").toString());
            }
        }
        
    }
    
    private class InitialiseMapRunnable implements Runnable {
        private Map<CidsBean, Collection<Geometry>> geometriesBuchungsblaetter;

        public InitialiseMapRunnable(Map<CidsBean, Collection<Geometry>> geometriesBuchungsblaetter) {
            this.geometriesBuchungsblaetter = geometriesBuchungsblaetter;
            if(features == null) {
                features = new HashMap<CidsBean, Collection<StyledFeature>>(this.geometriesBuchungsblaetter.size());
            }
        }

        @Override
        public void run() {
            final Collection<Geometry> geometries = new LinkedList<Geometry>();
            for(Entry<CidsBean, Collection<Geometry>> entry : geometriesBuchungsblaetter.entrySet()) {
                final Collection<StyledFeature> featuresOfBuchungsblatt = new LinkedList<StyledFeature>();
                
                for(Geometry geometry : entry.getValue()) {
                    geometries.add(geometry);
                    
                    final StyledFeature dsf = new DefaultStyledFeature();
                    dsf.setGeometry(geometry);
                    dsf.setFillingPaint(new Color(1, 0, 0, 0.5f));
                    featuresOfBuchungsblatt.add(dsf);
                }
                    
                features.put(entry.getKey(), featuresOfBuchungsblatt);
            }
            
            final ActiveLayerModel mappingModel = new ActiveLayerModel();
            mappingModel.setSrs(AlkisConstants.COMMONS.SRS_SERVICE);
            mappingModel.addHome(getBoundingBox(geometries));
            
            final SimpleWMS swms = new SimpleWMS(new SimpleWmsGetMapUrl(AlkisConstants.COMMONS.MAP_CALL_STRING));
            swms.setName("Buchungsblatt");
            
            // add the raster layer to the model
            mappingModel.addLayer(swms);
            // set the model
            map.setMappingModel(mappingModel);
            // initial positioning of the map
            final int duration = map.getAnimationDuration();
            map.setAnimationDuration(0);
            map.gotoInitialBoundingBox();
            // interaction mode
            map.setInteractionMode(MappingComponent.ZOOM);
            // finally when all configurations are done ...
            map.unlock();
            map.setInteractionMode("MUTE");
            
            for(final Collection<StyledFeature> featureList : features.values()) {
                map.getFeatureCollection().addFeatures(featureList);
            }
            
            map.setAnimationDuration(duration);
        }
        
        private XBoundingBox getBoundingBox(Collection<Geometry> geometries) {
            XBoundingBox result = null;
            for(Geometry geometry : geometries) {
                if(result == null) {
                    result = new XBoundingBox(geometry.getEnvelope().buffer(AlkisConstants.COMMONS.GEO_BUFFER));
                    result.setSrs(AlkisConstants.COMMONS.SRS_SERVICE);
                    result.setMetric(true);
                } else {
                    XBoundingBox temp = new XBoundingBox(geometry.getEnvelope().buffer(AlkisConstants.COMMONS.GEO_BUFFER));
                    temp.setSrs(AlkisConstants.COMMONS.SRS_SERVICE);
                    temp.setMetric(true);
                    
                    if(temp.getX1() < result.getX1()) {
                        result.setX1(temp.getX1());
                    }
                    if(temp.getY1() < result.getY1()) {
                        result.setY1(temp.getY1());
                    }
                    if(temp.getX2() > result.getX2()) {
                        result.setX2(temp.getX2());
                    }
                    if(temp.getY2() > result.getY2()) {
                        result.setY2(temp.getY2());
                    }
                }
            }
            
            return result;
        }
    }
    
    private class ChangeMapRunnable implements Runnable {
        private Collection<CidsBean> cidsBeans;
        private CidsBean cidsBeanToHighlight;
        
        public ChangeMapRunnable(final Collection<CidsBean> cidsBeans, final CidsBean cidsBeanToHighlight) {
            this.cidsBeans = cidsBeans;
            this.cidsBeanToHighlight = cidsBeanToHighlight;
        }
        
        @Override
        public void run() {
            final FeatureCollection featureCollection = map.getFeatureCollection();
            
            featureCollection.removeAllFeatures();
            
            for(CidsBean cidsBean : cidsBeans) {
                for(final StyledFeature feature : features.get(cidsBean)) {
                    if(cidsBean.equals(cidsBeanToHighlight)) {
                        if(feature.getFillingPaint().equals(COLOR_FEATURE_DEFAULT)) {
                            feature.setFillingPaint(COLOR_FEATURE_HIGHLIGHTED);
                        }
                    } else {
                        if(feature.getFillingPaint().equals(COLOR_FEATURE_HIGHLIGHTED)) {
                            feature.setFillingPaint(COLOR_FEATURE_DEFAULT);
                        }
                    }

                    featureCollection.addFeature(feature);
                }
            }
        }
    }
}
