/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.wunda.oab.objecteditors;

import org.openide.util.NbBundle;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  1.0
 */
public class Oab_GewaessereinzugsgebietEditor extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.cids.editors.DefaultBindableDateChooser defaultBindableDateChooserFrom;
    private de.cismet.cids.editors.DefaultBindableDateChooser defaultBindableDateChooserTo;
    private de.cismet.cids.editors.DefaultBindableReferenceCombo defaultBindableReferenceComboStatus;
    private javax.swing.Box.Filler hFill;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTo;
    private javax.swing.Box.Filler vFill;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form Oab_BerechnungEditor.
     */
    public Oab_GewaessereinzugsgebietEditor() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        defaultBindableDateChooserFrom = new de.cismet.cids.editors.DefaultBindableDateChooser();
        defaultBindableDateChooserTo = new de.cismet.cids.editors.DefaultBindableDateChooser();
        defaultBindableReferenceComboStatus = new de.cismet.cids.editors.DefaultBindableReferenceCombo();
        hFill = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        vFill = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(lblFrom, NbBundle.getMessage(Oab_GewaessereinzugsgebietEditor.class, "Oab_GewaessereinzugsgebietEditor.lblFrom.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
        add(lblFrom, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(lblTo, NbBundle.getMessage(Oab_GewaessereinzugsgebietEditor.class, "Oab_GewaessereinzugsgebietEditor.lblTo.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        add(lblTo, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(lblStatus, NbBundle.getMessage(Oab_GewaessereinzugsgebietEditor.class, "Oab_GewaessereinzugsgebietEditor.lblStatus.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        add(lblStatus, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 5, 5);
        add(defaultBindableDateChooserFrom, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(defaultBindableDateChooserTo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(defaultBindableReferenceComboStatus, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        add(hFill, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 1.0;
        add(vFill, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
}
